// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: assignment.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Late Policy Configuration
type LatePolicy struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	PenaltyPercentPerDay int32                  `protobuf:"varint,1,opt,name=penalty_percent_per_day,json=penaltyPercentPerDay,proto3" json:"penalty_percent_per_day,omitempty"` // Percentage deduction per day late (0-100)
	MaxLateDays          int32                  `protobuf:"varint,2,opt,name=max_late_days,json=maxLateDays,proto3" json:"max_late_days,omitempty"`                              // Maximum days late before zero (0 = no late submissions)
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *LatePolicy) Reset() {
	*x = LatePolicy{}
	mi := &file_assignment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatePolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatePolicy) ProtoMessage() {}

func (x *LatePolicy) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatePolicy.ProtoReflect.Descriptor instead.
func (*LatePolicy) Descriptor() ([]byte, []int) {
	return file_assignment_proto_rawDescGZIP(), []int{0}
}

func (x *LatePolicy) GetPenaltyPercentPerDay() int32 {
	if x != nil {
		return x.PenaltyPercentPerDay
	}
	return 0
}

func (x *LatePolicy) GetMaxLateDays() int32 {
	if x != nil {
		return x.MaxLateDays
	}
	return 0
}

// Assignment Message
type Assignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	MaxPoints     float64                `protobuf:"fixed64,5,opt,name=max_points,json=maxPoints,proto3" json:"max_points,omitempty"`
	DueDate       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	LatePolicy    *LatePolicy            `protobuf:"bytes,7,opt,name=late_policy,json=latePolicy,proto3" json:"late_policy,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Assignment) Reset() {
	*x = Assignment{}
	mi := &file_assignment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Assignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Assignment) ProtoMessage() {}

func (x *Assignment) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Assignment.ProtoReflect.Descriptor instead.
func (*Assignment) Descriptor() ([]byte, []int) {
	return file_assignment_proto_rawDescGZIP(), []int{1}
}

func (x *Assignment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Assignment) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *Assignment) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Assignment) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Assignment) GetMaxPoints() float64 {
	if x != nil {
		return x.MaxPoints
	}
	return 0
}

func (x *Assignment) GetDueDate() *timestamppb.Timestamp {
	if x != nil {
		return x.DueDate
	}
	return nil
}

func (x *Assignment) GetLatePolicy() *LatePolicy {
	if x != nil {
		return x.LatePolicy
	}
	return nil
}

func (x *Assignment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Assignment) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Submission Message
type Submission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AssignmentId  string                 `protobuf:"bytes,2,opt,name=assignment_id,json=assignmentId,proto3" json:"assignment_id,omitempty"`
	StudentId     string                 `protobuf:"bytes,3,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	FilePath      string                 `protobuf:"bytes,4,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	SubmittedAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=submitted_at,json=submittedAt,proto3" json:"submitted_at,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"` // submitted, graded, returned
	IsLate        bool                   `protobuf:"varint,7,opt,name=is_late,json=isLate,proto3" json:"is_late,omitempty"`
	DaysLate      int32                  `protobuf:"varint,8,opt,name=days_late,json=daysLate,proto3" json:"days_late,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Submission) Reset() {
	*x = Submission{}
	mi := &file_assignment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Submission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Submission) ProtoMessage() {}

func (x *Submission) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Submission.ProtoReflect.Descriptor instead.
func (*Submission) Descriptor() ([]byte, []int) {
	return file_assignment_proto_rawDescGZIP(), []int{2}
}

func (x *Submission) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Submission) GetAssignmentId() string {
	if x != nil {
		return x.AssignmentId
	}
	return ""
}

func (x *Submission) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *Submission) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *Submission) GetSubmittedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SubmittedAt
	}
	return nil
}

func (x *Submission) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Submission) GetIsLate() bool {
	if x != nil {
		return x.IsLate
	}
	return false
}

func (x *Submission) GetDaysLate() int32 {
	if x != nil {
		return x.DaysLate
	}
	return 0
}

func (x *Submission) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Submission) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Grade Message
type Grade struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SubmissionId  string                 `protobuf:"bytes,2,opt,name=submission_id,json=submissionId,proto3" json:"submission_id,omitempty"`
	StudentId     string                 `protobuf:"bytes,3,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	AssignmentId  string                 `protobuf:"bytes,4,opt,name=assignment_id,json=assignmentId,proto3" json:"assignment_id,omitempty"`
	Score         float64                `protobuf:"fixed64,5,opt,name=score,proto3" json:"score,omitempty"`
	AdjustedScore float64                `protobuf:"fixed64,6,opt,name=adjusted_score,json=adjustedScore,proto3" json:"adjusted_score,omitempty"` // After late penalty
	Feedback      string                 `protobuf:"bytes,7,opt,name=feedback,proto3" json:"feedback,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"` // draft, published
	GradedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=graded_at,json=gradedAt,proto3" json:"graded_at,omitempty"`
	PublishedAt   *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	GradedBy      string                 `protobuf:"bytes,11,opt,name=graded_by,json=gradedBy,proto3" json:"graded_by,omitempty"` // Instructor ID
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Grade) Reset() {
	*x = Grade{}
	mi := &file_assignment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Grade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Grade) ProtoMessage() {}

func (x *Grade) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Grade.ProtoReflect.Descriptor instead.
func (*Grade) Descriptor() ([]byte, []int) {
	return file_assignment_proto_rawDescGZIP(), []int{3}
}

func (x *Grade) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Grade) GetSubmissionId() string {
	if x != nil {
		return x.SubmissionId
	}
	return ""
}

func (x *Grade) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *Grade) GetAssignmentId() string {
	if x != nil {
		return x.AssignmentId
	}
	return ""
}

func (x *Grade) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Grade) GetAdjustedScore() float64 {
	if x != nil {
		return x.AdjustedScore
	}
	return 0
}

func (x *Grade) GetFeedback() string {
	if x != nil {
		return x.Feedback
	}
	return ""
}

func (x *Grade) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Grade) GetGradedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GradedAt
	}
	return nil
}

func (x *Grade) GetPublishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishedAt
	}
	return nil
}

func (x *Grade) GetGradedBy() string {
	if x != nil {
		return x.GradedBy
	}
	return ""
}

func (x *Grade) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Grade) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Assignment Service Messages
type CreateAssignmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	MaxPoints     float64                `protobuf:"fixed64,4,opt,name=max_points,json=maxPoints,proto3" json:"max_points,omitempty"`
	DueDate       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	LatePolicy    *LatePolicy            `protobuf:"bytes,6,opt,name=late_policy,json=latePolicy,proto3" json:"late_policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAssignmentRequest) Reset() {
	*x = CreateAssignmentRequest{}
	mi := &file_assignment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAssignmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAssignmentRequest) ProtoMessage() {}

func (x *CreateAssignmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAssignmentRequest.ProtoReflect.Descriptor instead.
func (*CreateAssignmentRequest) Descriptor() ([]byte, []int) {
	return file_assignment_proto_rawDescGZIP(), []int{4}
}

func (x *CreateAssignmentRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *CreateAssignmentRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateAssignmentRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateAssignmentRequest) GetMaxPoints() float64 {
	if x != nil {
		return x.MaxPoints
	}
	return 0
}

func (x *CreateAssignmentRequest) GetDueDate() *timestamppb.Timestamp {
	if x != nil {
		return x.DueDate
	}
	return nil
}

func (x *CreateAssignmentRequest) GetLatePolicy() *LatePolicy {
	if x != nil {
		return x.LatePolicy
	}
	return nil
}

type CreateAssignmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assignment    *Assignment            `protobuf:"bytes,1,opt,name=assignment,proto3" json:"assignment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAssignmentResponse) Reset() {
	*x = CreateAssignmentResponse{}
	mi := &file_assignment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAssignmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAssignmentResponse) ProtoMessage() {}

func (x *CreateAssignmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAssignmentResponse.ProtoReflect.Descriptor instead.
func (*CreateAssignmentResponse) Descriptor() ([]byte, []int) {
	return file_assignment_proto_rawDescGZIP(), []int{5}
}

func (x *CreateAssignmentResponse) GetAssignment() *Assignment {
	if x != nil {
		return x.Assignment
	}
	return nil
}

type GetAssignmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssignmentRequest) Reset() {
	*x = GetAssignmentRequest{}
	mi := &file_assignment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssignmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssignmentRequest) ProtoMessage() {}

func (x *GetAssignmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssignmentRequest.ProtoReflect.Descriptor instead.
func (*GetAssignmentRequest) Descriptor() ([]byte, []int) {
	return file_assignment_proto_rawDescGZIP(), []int{6}
}

func (x *GetAssignmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAssignmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assignment    *Assignment            `protobuf:"bytes,1,opt,name=assignment,proto3" json:"assignment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssignmentResponse) Reset() {
	*x = GetAssignmentResponse{}
	mi := &file_assignment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssignmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssignmentResponse) ProtoMessage() {}

func (x *GetAssignmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssignmentResponse.ProtoReflect.Descriptor instead.
func (*GetAssignmentResponse) Descriptor() ([]byte, []int) {
	return file_assignment_proto_rawDescGZIP(), []int{7}
}

func (x *GetAssignmentResponse) GetAssignment() *Assignment {
	if x != nil {
		return x.Assignment
	}
	return nil
}

type UpdateAssignmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	MaxPoints     float64                `protobuf:"fixed64,4,opt,name=max_points,json=maxPoints,proto3" json:"max_points,omitempty"`
	DueDate       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	LatePolicy    *LatePolicy            `protobuf:"bytes,6,opt,name=late_policy,json=latePolicy,proto3" json:"late_policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAssignmentRequest) Reset() {
	*x = UpdateAssignmentRequest{}
	mi := &file_assignment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAssignmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAssignmentRequest) ProtoMessage() {}

func (x *UpdateAssignmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAssignmentRequest.ProtoReflect.Descriptor instead.
func (*UpdateAssignmentRequest) Descriptor() ([]byte, []int) {
	return file_assignment_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateAssignmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateAssignmentRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateAssignmentRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateAssignmentRequest) GetMaxPoints() float64 {
	if x != nil {
		return x.MaxPoints
	}
	return 0
}

func (x *UpdateAssignmentRequest) GetDueDate() *timestamppb.Timestamp {
	if x != nil {
		return x.DueDate
	}
	return nil
}

func (x *UpdateAssignmentRequest) GetLatePolicy() *LatePolicy {
	if x != nil {
		return x.LatePolicy
	}
	return nil
}

type UpdateAssignmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assignment    *Assignment            `protobuf:"bytes,1,opt,name=assignment,proto3" json:"assignment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAssignmentResponse) Reset() {
	*x = UpdateAssignmentResponse{}
	mi := &file_assignment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAssignmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAssignmentResponse) ProtoMessage() {}

func (x *UpdateAssignmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAssignmentResponse.ProtoReflect.Descriptor instead.
func (*UpdateAssignmentResponse) Descriptor() ([]byte, []int) {
	return file_assignment_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateAssignmentResponse) GetAssignment() *Assignment {
	if x != nil {
		return x.Assignment
	}
	return nil
}

type DeleteAssignmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAssignmentRequest) Reset() {
	*x = DeleteAssignmentRequest{}
	mi := &file_assignment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAssignmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAssignmentRequest) ProtoMessage() {}

func (x *DeleteAssignmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAssignmentRequest.ProtoReflect.Descriptor instead.
func (*DeleteAssignmentRequest) Descriptor() ([]byte, []int) {
	return file_assignment_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteAssignmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteAssignmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAssignmentResponse) Reset() {
	*x = DeleteAssignmentResponse{}
	mi := &file_assignment_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAssignmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAssignmentResponse) ProtoMessage() {}

func (x *DeleteAssignmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAssignmentResponse.ProtoReflect.Descriptor instead.
func (*DeleteAssignmentResponse) Descriptor() ([]byte, []int) {
	return file_assignment_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteAssignmentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListAssignmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAssignmentsRequest) Reset() {
	*x = ListAssignmentsRequest{}
	mi := &file_assignment_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAssignmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAssignmentsRequest) ProtoMessage() {}

func (x *ListAssignmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAssignmentsRequest.ProtoReflect.Descriptor instead.
func (*ListAssignmentsRequest) Descriptor() ([]byte, []int) {
	return file_assignment_proto_rawDescGZIP(), []int{12}
}

func (x *ListAssignmentsRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *ListAssignmentsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListAssignmentsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListAssignmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assignments   []*Assignment          `protobuf:"bytes,1,rep,name=assignments,proto3" json:"assignments,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAssignmentsResponse) Reset() {
	*x = ListAssignmentsResponse{}
	mi := &file_assignment_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAssignmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAssignmentsResponse) ProtoMessage() {}

func (x *ListAssignmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAssignmentsResponse.ProtoReflect.Descriptor instead.
func (*ListAssignmentsResponse) Descriptor() ([]byte, []int) {
	return file_assignment_proto_rawDescGZIP(), []int{13}
}

func (x *ListAssignmentsResponse) GetAssignments() []*Assignment {
	if x != nil {
		return x.Assignments
	}
	return nil
}

func (x *ListAssignmentsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListAssignmentsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListAssignmentsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// Submission Service Messages
type SubmitAssignmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssignmentId  string                 `protobuf:"bytes,1,opt,name=assignment_id,json=assignmentId,proto3" json:"assignment_id,omitempty"`
	StudentId     string                 `protobuf:"bytes,2,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	FileContent   []byte                 `protobuf:"bytes,3,opt,name=file_content,json=fileContent,proto3" json:"file_content,omitempty"`
	FileName      string                 `protobuf:"bytes,4,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	ContentType   string                 `protobuf:"bytes,5,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitAssignmentRequest) Reset() {
	*x = SubmitAssignmentRequest{}
	mi := &file_assignment_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitAssignmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitAssignmentRequest) ProtoMessage() {}

func (x *SubmitAssignmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitAssignmentRequest.ProtoReflect.Descriptor instead.
func (*SubmitAssignmentRequest) Descriptor() ([]byte, []int) {
	return file_assignment_proto_rawDescGZIP(), []int{14}
}

func (x *SubmitAssignmentRequest) GetAssignmentId() string {
	if x != nil {
		return x.AssignmentId
	}
	return ""
}

func (x *SubmitAssignmentRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *SubmitAssignmentRequest) GetFileContent() []byte {
	if x != nil {
		return x.FileContent
	}
	return nil
}

func (x *SubmitAssignmentRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *SubmitAssignmentRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type SubmitAssignmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Submission    *Submission            `protobuf:"bytes,1,opt,name=submission,proto3" json:"submission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitAssignmentResponse) Reset() {
	*x = SubmitAssignmentResponse{}
	mi := &file_assignment_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitAssignmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitAssignmentResponse) ProtoMessage() {}

func (x *SubmitAssignmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitAssignmentResponse.ProtoReflect.Descriptor instead.
func (*SubmitAssignmentResponse) Descriptor() ([]byte, []int) {
	return file_assignment_proto_rawDescGZIP(), []int{15}
}

func (x *SubmitAssignmentResponse) GetSubmission() *Submission {
	if x != nil {
		return x.Submission
	}
	return nil
}

type GetSubmissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubmissionRequest) Reset() {
	*x = GetSubmissionRequest{}
	mi := &file_assignment_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubmissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubmissionRequest) ProtoMessage() {}

func (x *GetSubmissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubmissionRequest.ProtoReflect.Descriptor instead.
func (*GetSubmissionRequest) Descriptor() ([]byte, []int) {
	return file_assignment_proto_rawDescGZIP(), []int{16}
}

func (x *GetSubmissionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetSubmissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Submission    *Submission            `protobuf:"bytes,1,opt,name=submission,proto3" json:"submission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubmissionResponse) Reset() {
	*x = GetSubmissionResponse{}
	mi := &file_assignment_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubmissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubmissionResponse) ProtoMessage() {}

func (x *GetSubmissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubmissionResponse.ProtoReflect.Descriptor instead.
func (*GetSubmissionResponse) Descriptor() ([]byte, []int) {
	return file_assignment_proto_rawDescGZIP(), []int{17}
}

func (x *GetSubmissionResponse) GetSubmission() *Submission {
	if x != nil {
		return x.Submission
	}
	return nil
}

type ListSubmissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssignmentId  string                 `protobuf:"bytes,1,opt,name=assignment_id,json=assignmentId,proto3" json:"assignment_id,omitempty"`
	SortBy        string                 `protobuf:"bytes,2,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"` // submitted_at, student_id
	Order         string                 `protobuf:"bytes,3,opt,name=order,proto3" json:"order,omitempty"`                 // asc, desc
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSubmissionsRequest) Reset() {
	*x = ListSubmissionsRequest{}
	mi := &file_assignment_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubmissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubmissionsRequest) ProtoMessage() {}

func (x *ListSubmissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubmissionsRequest.ProtoReflect.Descriptor instead.
func (*ListSubmissionsRequest) Descriptor() ([]byte, []int) {
	return file_assignment_proto_rawDescGZIP(), []int{18}
}

func (x *ListSubmissionsRequest) GetAssignmentId() string {
	if x != nil {
		return x.AssignmentId
	}
	return ""
}

func (x *ListSubmissionsRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *ListSubmissionsRequest) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

type ListSubmissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Submissions   []*Submission          `protobuf:"bytes,1,rep,name=submissions,proto3" json:"submissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSubmissionsResponse) Reset() {
	*x = ListSubmissionsResponse{}
	mi := &file_assignment_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubmissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubmissionsResponse) ProtoMessage() {}

func (x *ListSubmissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubmissionsResponse.ProtoReflect.Descriptor instead.
func (*ListSubmissionsResponse) Descriptor() ([]byte, []int) {
	return file_assignment_proto_rawDescGZIP(), []int{19}
}

func (x *ListSubmissionsResponse) GetSubmissions() []*Submission {
	if x != nil {
		return x.Submissions
	}
	return nil
}

type ListStudentSubmissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStudentSubmissionsRequest) Reset() {
	*x = ListStudentSubmissionsRequest{}
	mi := &file_assignment_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStudentSubmissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStudentSubmissionsRequest) ProtoMessage() {}

func (x *ListStudentSubmissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStudentSubmissionsRequest.ProtoReflect.Descriptor instead.
func (*ListStudentSubmissionsRequest) Descriptor() ([]byte, []int) {
	return file_assignment_proto_rawDescGZIP(), []int{20}
}

func (x *ListStudentSubmissionsRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *ListStudentSubmissionsRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type ListStudentSubmissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Submissions   []*Submission          `protobuf:"bytes,1,rep,name=submissions,proto3" json:"submissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStudentSubmissionsResponse) Reset() {
	*x = ListStudentSubmissionsResponse{}
	mi := &file_assignment_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStudentSubmissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStudentSubmissionsResponse) ProtoMessage() {}

func (x *ListStudentSubmissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStudentSubmissionsResponse.ProtoReflect.Descriptor instead.
func (*ListStudentSubmissionsResponse) Descriptor() ([]byte, []int) {
	return file_assignment_proto_rawDescGZIP(), []int{21}
}

func (x *ListStudentSubmissionsResponse) GetSubmissions() []*Submission {
	if x != nil {
		return x.Submissions
	}
	return nil
}

// Grading Service Messages
type CreateGradeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubmissionId  string                 `protobuf:"bytes,1,opt,name=submission_id,json=submissionId,proto3" json:"submission_id,omitempty"`
	Score         float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	Feedback      string                 `protobuf:"bytes,3,opt,name=feedback,proto3" json:"feedback,omitempty"`
	GradedBy      string                 `protobuf:"bytes,4,opt,name=graded_by,json=gradedBy,proto3" json:"graded_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGradeRequest) Reset() {
	*x = CreateGradeRequest{}
	mi := &file_assignment_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGradeRequest) ProtoMessage() {}

func (x *CreateGradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGradeRequest.ProtoReflect.Descriptor instead.
func (*CreateGradeRequest) Descriptor() ([]byte, []int) {
	return file_assignment_proto_rawDescGZIP(), []int{22}
}

func (x *CreateGradeRequest) GetSubmissionId() string {
	if x != nil {
		return x.SubmissionId
	}
	return ""
}

func (x *CreateGradeRequest) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *CreateGradeRequest) GetFeedback() string {
	if x != nil {
		return x.Feedback
	}
	return ""
}

func (x *CreateGradeRequest) GetGradedBy() string {
	if x != nil {
		return x.GradedBy
	}
	return ""
}

type CreateGradeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Grade         *Grade                 `protobuf:"bytes,1,opt,name=grade,proto3" json:"grade,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGradeResponse) Reset() {
	*x = CreateGradeResponse{}
	mi := &file_assignment_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGradeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGradeResponse) ProtoMessage() {}

func (x *CreateGradeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGradeResponse.ProtoReflect.Descriptor instead.
func (*CreateGradeResponse) Descriptor() ([]byte, []int) {
	return file_assignment_proto_rawDescGZIP(), []int{23}
}

func (x *CreateGradeResponse) GetGrade() *Grade {
	if x != nil {
		return x.Grade
	}
	return nil
}

type UpdateGradeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Score         float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	Feedback      string                 `protobuf:"bytes,3,opt,name=feedback,proto3" json:"feedback,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGradeRequest) Reset() {
	*x = UpdateGradeRequest{}
	mi := &file_assignment_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGradeRequest) ProtoMessage() {}

func (x *UpdateGradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGradeRequest.ProtoReflect.Descriptor instead.
func (*UpdateGradeRequest) Descriptor() ([]byte, []int) {
	return file_assignment_proto_rawDescGZIP(), []int{24}
}

func (x *UpdateGradeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateGradeRequest) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *UpdateGradeRequest) GetFeedback() string {
	if x != nil {
		return x.Feedback
	}
	return ""
}

type UpdateGradeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Grade         *Grade                 `protobuf:"bytes,1,opt,name=grade,proto3" json:"grade,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGradeResponse) Reset() {
	*x = UpdateGradeResponse{}
	mi := &file_assignment_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGradeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGradeResponse) ProtoMessage() {}

func (x *UpdateGradeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGradeResponse.ProtoReflect.Descriptor instead.
func (*UpdateGradeResponse) Descriptor() ([]byte, []int) {
	return file_assignment_proto_rawDescGZIP(), []int{25}
}

func (x *UpdateGradeResponse) GetGrade() *Grade {
	if x != nil {
		return x.Grade
	}
	return nil
}

type PublishGradeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishGradeRequest) Reset() {
	*x = PublishGradeRequest{}
	mi := &file_assignment_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishGradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishGradeRequest) ProtoMessage() {}

func (x *PublishGradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishGradeRequest.ProtoReflect.Descriptor instead.
func (*PublishGradeRequest) Descriptor() ([]byte, []int) {
	return file_assignment_proto_rawDescGZIP(), []int{26}
}

func (x *PublishGradeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PublishGradeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Grade         *Grade                 `protobuf:"bytes,1,opt,name=grade,proto3" json:"grade,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishGradeResponse) Reset() {
	*x = PublishGradeResponse{}
	mi := &file_assignment_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishGradeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishGradeResponse) ProtoMessage() {}

func (x *PublishGradeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishGradeResponse.ProtoReflect.Descriptor instead.
func (*PublishGradeResponse) Descriptor() ([]byte, []int) {
	return file_assignment_proto_rawDescGZIP(), []int{27}
}

func (x *PublishGradeResponse) GetGrade() *Grade {
	if x != nil {
		return x.Grade
	}
	return nil
}

type GetGradeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGradeRequest) Reset() {
	*x = GetGradeRequest{}
	mi := &file_assignment_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGradeRequest) ProtoMessage() {}

func (x *GetGradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGradeRequest.ProtoReflect.Descriptor instead.
func (*GetGradeRequest) Descriptor() ([]byte, []int) {
	return file_assignment_proto_rawDescGZIP(), []int{28}
}

func (x *GetGradeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetGradeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Grade         *Grade                 `protobuf:"bytes,1,opt,name=grade,proto3" json:"grade,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGradeResponse) Reset() {
	*x = GetGradeResponse{}
	mi := &file_assignment_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGradeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGradeResponse) ProtoMessage() {}

func (x *GetGradeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGradeResponse.ProtoReflect.Descriptor instead.
func (*GetGradeResponse) Descriptor() ([]byte, []int) {
	return file_assignment_proto_rawDescGZIP(), []int{29}
}

func (x *GetGradeResponse) GetGrade() *Grade {
	if x != nil {
		return x.Grade
	}
	return nil
}

// Gradebook Service Messages
type GetStudentGradebookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudentGradebookRequest) Reset() {
	*x = GetStudentGradebookRequest{}
	mi := &file_assignment_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentGradebookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentGradebookRequest) ProtoMessage() {}

func (x *GetStudentGradebookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentGradebookRequest.ProtoReflect.Descriptor instead.
func (*GetStudentGradebookRequest) Descriptor() ([]byte, []int) {
	return file_assignment_proto_rawDescGZIP(), []int{30}
}

func (x *GetStudentGradebookRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *GetStudentGradebookRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type GradebookEntry struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AssignmentId    string                 `protobuf:"bytes,1,opt,name=assignment_id,json=assignmentId,proto3" json:"assignment_id,omitempty"`
	AssignmentTitle string                 `protobuf:"bytes,2,opt,name=assignment_title,json=assignmentTitle,proto3" json:"assignment_title,omitempty"`
	MaxPoints       float64                `protobuf:"fixed64,3,opt,name=max_points,json=maxPoints,proto3" json:"max_points,omitempty"`
	Score           float64                `protobuf:"fixed64,4,opt,name=score,proto3" json:"score,omitempty"`
	AdjustedScore   float64                `protobuf:"fixed64,5,opt,name=adjusted_score,json=adjustedScore,proto3" json:"adjusted_score,omitempty"`
	Status          string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	DueDate         *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	SubmittedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=submitted_at,json=submittedAt,proto3" json:"submitted_at,omitempty"`
	IsLate          bool                   `protobuf:"varint,9,opt,name=is_late,json=isLate,proto3" json:"is_late,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GradebookEntry) Reset() {
	*x = GradebookEntry{}
	mi := &file_assignment_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradebookEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradebookEntry) ProtoMessage() {}

func (x *GradebookEntry) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradebookEntry.ProtoReflect.Descriptor instead.
func (*GradebookEntry) Descriptor() ([]byte, []int) {
	return file_assignment_proto_rawDescGZIP(), []int{31}
}

func (x *GradebookEntry) GetAssignmentId() string {
	if x != nil {
		return x.AssignmentId
	}
	return ""
}

func (x *GradebookEntry) GetAssignmentTitle() string {
	if x != nil {
		return x.AssignmentTitle
	}
	return ""
}

func (x *GradebookEntry) GetMaxPoints() float64 {
	if x != nil {
		return x.MaxPoints
	}
	return 0
}

func (x *GradebookEntry) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *GradebookEntry) GetAdjustedScore() float64 {
	if x != nil {
		return x.AdjustedScore
	}
	return 0
}

func (x *GradebookEntry) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GradebookEntry) GetDueDate() *timestamppb.Timestamp {
	if x != nil {
		return x.DueDate
	}
	return nil
}

func (x *GradebookEntry) GetSubmittedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SubmittedAt
	}
	return nil
}

func (x *GradebookEntry) GetIsLate() bool {
	if x != nil {
		return x.IsLate
	}
	return false
}

type GetStudentGradebookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Entries       []*GradebookEntry      `protobuf:"bytes,3,rep,name=entries,proto3" json:"entries,omitempty"`
	TotalPoints   float64                `protobuf:"fixed64,4,opt,name=total_points,json=totalPoints,proto3" json:"total_points,omitempty"`
	EarnedPoints  float64                `protobuf:"fixed64,5,opt,name=earned_points,json=earnedPoints,proto3" json:"earned_points,omitempty"`
	Percentage    float64                `protobuf:"fixed64,6,opt,name=percentage,proto3" json:"percentage,omitempty"`
	LetterGrade   string                 `protobuf:"bytes,7,opt,name=letter_grade,json=letterGrade,proto3" json:"letter_grade,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudentGradebookResponse) Reset() {
	*x = GetStudentGradebookResponse{}
	mi := &file_assignment_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentGradebookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentGradebookResponse) ProtoMessage() {}

func (x *GetStudentGradebookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentGradebookResponse.ProtoReflect.Descriptor instead.
func (*GetStudentGradebookResponse) Descriptor() ([]byte, []int) {
	return file_assignment_proto_rawDescGZIP(), []int{32}
}

func (x *GetStudentGradebookResponse) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *GetStudentGradebookResponse) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *GetStudentGradebookResponse) GetEntries() []*GradebookEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *GetStudentGradebookResponse) GetTotalPoints() float64 {
	if x != nil {
		return x.TotalPoints
	}
	return 0
}

func (x *GetStudentGradebookResponse) GetEarnedPoints() float64 {
	if x != nil {
		return x.EarnedPoints
	}
	return 0
}

func (x *GetStudentGradebookResponse) GetPercentage() float64 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

func (x *GetStudentGradebookResponse) GetLetterGrade() string {
	if x != nil {
		return x.LetterGrade
	}
	return ""
}

type GetCourseGradebookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseGradebookRequest) Reset() {
	*x = GetCourseGradebookRequest{}
	mi := &file_assignment_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseGradebookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseGradebookRequest) ProtoMessage() {}

func (x *GetCourseGradebookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseGradebookRequest.ProtoReflect.Descriptor instead.
func (*GetCourseGradebookRequest) Descriptor() ([]byte, []int) {
	return file_assignment_proto_rawDescGZIP(), []int{33}
}

func (x *GetCourseGradebookRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type StudentGradeSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	StudentName   string                 `protobuf:"bytes,2,opt,name=student_name,json=studentName,proto3" json:"student_name,omitempty"`
	TotalPoints   float64                `protobuf:"fixed64,3,opt,name=total_points,json=totalPoints,proto3" json:"total_points,omitempty"`
	EarnedPoints  float64                `protobuf:"fixed64,4,opt,name=earned_points,json=earnedPoints,proto3" json:"earned_points,omitempty"`
	Percentage    float64                `protobuf:"fixed64,5,opt,name=percentage,proto3" json:"percentage,omitempty"`
	LetterGrade   string                 `protobuf:"bytes,6,opt,name=letter_grade,json=letterGrade,proto3" json:"letter_grade,omitempty"`
	Entries       []*GradebookEntry      `protobuf:"bytes,7,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentGradeSummary) Reset() {
	*x = StudentGradeSummary{}
	mi := &file_assignment_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentGradeSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentGradeSummary) ProtoMessage() {}

func (x *StudentGradeSummary) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentGradeSummary.ProtoReflect.Descriptor instead.
func (*StudentGradeSummary) Descriptor() ([]byte, []int) {
	return file_assignment_proto_rawDescGZIP(), []int{34}
}

func (x *StudentGradeSummary) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *StudentGradeSummary) GetStudentName() string {
	if x != nil {
		return x.StudentName
	}
	return ""
}

func (x *StudentGradeSummary) GetTotalPoints() float64 {
	if x != nil {
		return x.TotalPoints
	}
	return 0
}

func (x *StudentGradeSummary) GetEarnedPoints() float64 {
	if x != nil {
		return x.EarnedPoints
	}
	return 0
}

func (x *StudentGradeSummary) GetPercentage() float64 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

func (x *StudentGradeSummary) GetLetterGrade() string {
	if x != nil {
		return x.LetterGrade
	}
	return ""
}

func (x *StudentGradeSummary) GetEntries() []*GradebookEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type GetCourseGradebookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Students      []*StudentGradeSummary `protobuf:"bytes,2,rep,name=students,proto3" json:"students,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseGradebookResponse) Reset() {
	*x = GetCourseGradebookResponse{}
	mi := &file_assignment_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseGradebookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseGradebookResponse) ProtoMessage() {}

func (x *GetCourseGradebookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseGradebookResponse.ProtoReflect.Descriptor instead.
func (*GetCourseGradebookResponse) Descriptor() ([]byte, []int) {
	return file_assignment_proto_rawDescGZIP(), []int{35}
}

func (x *GetCourseGradebookResponse) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *GetCourseGradebookResponse) GetStudents() []*StudentGradeSummary {
	if x != nil {
		return x.Students
	}
	return nil
}

type GetGradeStatisticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssignmentId  string                 `protobuf:"bytes,1,opt,name=assignment_id,json=assignmentId,proto3" json:"assignment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGradeStatisticsRequest) Reset() {
	*x = GetGradeStatisticsRequest{}
	mi := &file_assignment_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGradeStatisticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGradeStatisticsRequest) ProtoMessage() {}

func (x *GetGradeStatisticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGradeStatisticsRequest.ProtoReflect.Descriptor instead.
func (*GetGradeStatisticsRequest) Descriptor() ([]byte, []int) {
	return file_assignment_proto_rawDescGZIP(), []int{36}
}

func (x *GetGradeStatisticsRequest) GetAssignmentId() string {
	if x != nil {
		return x.AssignmentId
	}
	return ""
}

type GradeStatistics struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AssignmentId     string                 `protobuf:"bytes,1,opt,name=assignment_id,json=assignmentId,proto3" json:"assignment_id,omitempty"`
	TotalSubmissions int32                  `protobuf:"varint,2,opt,name=total_submissions,json=totalSubmissions,proto3" json:"total_submissions,omitempty"`
	GradedCount      int32                  `protobuf:"varint,3,opt,name=graded_count,json=gradedCount,proto3" json:"graded_count,omitempty"`
	Mean             float64                `protobuf:"fixed64,4,opt,name=mean,proto3" json:"mean,omitempty"`
	Median           float64                `protobuf:"fixed64,5,opt,name=median,proto3" json:"median,omitempty"`
	StdDeviation     float64                `protobuf:"fixed64,6,opt,name=std_deviation,json=stdDeviation,proto3" json:"std_deviation,omitempty"`
	MinScore         float64                `protobuf:"fixed64,7,opt,name=min_score,json=minScore,proto3" json:"min_score,omitempty"`
	MaxScore         float64                `protobuf:"fixed64,8,opt,name=max_score,json=maxScore,proto3" json:"max_score,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GradeStatistics) Reset() {
	*x = GradeStatistics{}
	mi := &file_assignment_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradeStatistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradeStatistics) ProtoMessage() {}

func (x *GradeStatistics) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradeStatistics.ProtoReflect.Descriptor instead.
func (*GradeStatistics) Descriptor() ([]byte, []int) {
	return file_assignment_proto_rawDescGZIP(), []int{37}
}

func (x *GradeStatistics) GetAssignmentId() string {
	if x != nil {
		return x.AssignmentId
	}
	return ""
}

func (x *GradeStatistics) GetTotalSubmissions() int32 {
	if x != nil {
		return x.TotalSubmissions
	}
	return 0
}

func (x *GradeStatistics) GetGradedCount() int32 {
	if x != nil {
		return x.GradedCount
	}
	return 0
}

func (x *GradeStatistics) GetMean() float64 {
	if x != nil {
		return x.Mean
	}
	return 0
}

func (x *GradeStatistics) GetMedian() float64 {
	if x != nil {
		return x.Median
	}
	return 0
}

func (x *GradeStatistics) GetStdDeviation() float64 {
	if x != nil {
		return x.StdDeviation
	}
	return 0
}

func (x *GradeStatistics) GetMinScore() float64 {
	if x != nil {
		return x.MinScore
	}
	return 0
}

func (x *GradeStatistics) GetMaxScore() float64 {
	if x != nil {
		return x.MaxScore
	}
	return 0
}

type GetGradeStatisticsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Statistics    *GradeStatistics       `protobuf:"bytes,1,opt,name=statistics,proto3" json:"statistics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGradeStatisticsResponse) Reset() {
	*x = GetGradeStatisticsResponse{}
	mi := &file_assignment_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGradeStatisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGradeStatisticsResponse) ProtoMessage() {}

func (x *GetGradeStatisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGradeStatisticsResponse.ProtoReflect.Descriptor instead.
func (*GetGradeStatisticsResponse) Descriptor() ([]byte, []int) {
	return file_assignment_proto_rawDescGZIP(), []int{38}
}

func (x *GetGradeStatisticsResponse) GetStatistics() *GradeStatistics {
	if x != nil {
		return x.Statistics
	}
	return nil
}

type ExportGradesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"` // csv, json
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportGradesRequest) Reset() {
	*x = ExportGradesRequest{}
	mi := &file_assignment_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportGradesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportGradesRequest) ProtoMessage() {}

func (x *ExportGradesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportGradesRequest.ProtoReflect.Descriptor instead.
func (*ExportGradesRequest) Descriptor() ([]byte, []int) {
	return file_assignment_proto_rawDescGZIP(), []int{39}
}

func (x *ExportGradesRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *ExportGradesRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type ExportGradesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportGradesResponse) Reset() {
	*x = ExportGradesResponse{}
	mi := &file_assignment_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportGradesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportGradesResponse) ProtoMessage() {}

func (x *ExportGradesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportGradesResponse.ProtoReflect.Descriptor instead.
func (*ExportGradesResponse) Descriptor() ([]byte, []int) {
	return file_assignment_proto_rawDescGZIP(), []int{40}
}

func (x *ExportGradesResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ExportGradesResponse) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

// Health Check
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_assignment_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_assignment_proto_rawDescGZIP(), []int{41}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Timestamp     string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_assignment_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_assignment_proto_rawDescGZIP(), []int{42}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *HealthCheckResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

var File_assignment_proto protoreflect.FileDescriptor

const file_assignment_proto_rawDesc = "" +
	"\n" +
	"\x10assignment.proto\x12\n" +
	"assignment\x1a\x1fgoogle/protobuf/timestamp.proto\"g\n" +
	"\n" +
	"LatePolicy\x125\n" +
	"\x17penalty_percent_per_day\x18\x01 \x01(\x05R\x14penaltyPercentPerDay\x12\"\n" +
	"\rmax_late_days\x18\x02 \x01(\x05R\vmaxLateDays\"\xf6\x02\n" +
	"\n" +
	"Assignment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"max_points\x18\x05 \x01(\x01R\tmaxPoints\x125\n" +
	"\bdue_date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\adueDate\x127\n" +
	"\vlate_policy\x18\a \x01(\v2\x16.assignment.LatePolicyR\n" +
	"latePolicy\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x80\x03\n" +
	"\n" +
	"Submission\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rassignment_id\x18\x02 \x01(\tR\fassignmentId\x12\x1d\n" +
	"\n" +
	"student_id\x18\x03 \x01(\tR\tstudentId\x12\x1b\n" +
	"\tfile_path\x18\x04 \x01(\tR\bfilePath\x12=\n" +
	"\fsubmitted_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vsubmittedAt\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x17\n" +
	"\ais_late\x18\a \x01(\bR\x06isLate\x12\x1b\n" +
	"\tdays_late\x18\b \x01(\x05R\bdaysLate\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xfc\x03\n" +
	"\x05Grade\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rsubmission_id\x18\x02 \x01(\tR\fsubmissionId\x12\x1d\n" +
	"\n" +
	"student_id\x18\x03 \x01(\tR\tstudentId\x12#\n" +
	"\rassignment_id\x18\x04 \x01(\tR\fassignmentId\x12\x14\n" +
	"\x05score\x18\x05 \x01(\x01R\x05score\x12%\n" +
	"\x0eadjusted_score\x18\x06 \x01(\x01R\radjustedScore\x12\x1a\n" +
	"\bfeedback\x18\a \x01(\tR\bfeedback\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x127\n" +
	"\tgraded_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\bgradedAt\x12=\n" +
	"\fpublished_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\vpublishedAt\x12\x1b\n" +
	"\tgraded_by\x18\v \x01(\tR\bgradedBy\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xfd\x01\n" +
	"\x17CreateAssignmentRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"max_points\x18\x04 \x01(\x01R\tmaxPoints\x125\n" +
	"\bdue_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\adueDate\x127\n" +
	"\vlate_policy\x18\x06 \x01(\v2\x16.assignment.LatePolicyR\n" +
	"latePolicy\"R\n" +
	"\x18CreateAssignmentResponse\x126\n" +
	"\n" +
	"assignment\x18\x01 \x01(\v2\x16.assignment.AssignmentR\n" +
	"assignment\"&\n" +
	"\x14GetAssignmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"O\n" +
	"\x15GetAssignmentResponse\x126\n" +
	"\n" +
	"assignment\x18\x01 \x01(\v2\x16.assignment.AssignmentR\n" +
	"assignment\"\xf0\x01\n" +
	"\x17UpdateAssignmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"max_points\x18\x04 \x01(\x01R\tmaxPoints\x125\n" +
	"\bdue_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\adueDate\x127\n" +
	"\vlate_policy\x18\x06 \x01(\v2\x16.assignment.LatePolicyR\n" +
	"latePolicy\"R\n" +
	"\x18UpdateAssignmentResponse\x126\n" +
	"\n" +
	"assignment\x18\x01 \x01(\v2\x16.assignment.AssignmentR\n" +
	"assignment\")\n" +
	"\x17DeleteAssignmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"4\n" +
	"\x18DeleteAssignmentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"f\n" +
	"\x16ListAssignmentsRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\x9a\x01\n" +
	"\x17ListAssignmentsResponse\x128\n" +
	"\vassignments\x18\x01 \x03(\v2\x16.assignment.AssignmentR\vassignments\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\xc0\x01\n" +
	"\x17SubmitAssignmentRequest\x12#\n" +
	"\rassignment_id\x18\x01 \x01(\tR\fassignmentId\x12\x1d\n" +
	"\n" +
	"student_id\x18\x02 \x01(\tR\tstudentId\x12!\n" +
	"\ffile_content\x18\x03 \x01(\fR\vfileContent\x12\x1b\n" +
	"\tfile_name\x18\x04 \x01(\tR\bfileName\x12!\n" +
	"\fcontent_type\x18\x05 \x01(\tR\vcontentType\"R\n" +
	"\x18SubmitAssignmentResponse\x126\n" +
	"\n" +
	"submission\x18\x01 \x01(\v2\x16.assignment.SubmissionR\n" +
	"submission\"&\n" +
	"\x14GetSubmissionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"O\n" +
	"\x15GetSubmissionResponse\x126\n" +
	"\n" +
	"submission\x18\x01 \x01(\v2\x16.assignment.SubmissionR\n" +
	"submission\"l\n" +
	"\x16ListSubmissionsRequest\x12#\n" +
	"\rassignment_id\x18\x01 \x01(\tR\fassignmentId\x12\x17\n" +
	"\asort_by\x18\x02 \x01(\tR\x06sortBy\x12\x14\n" +
	"\x05order\x18\x03 \x01(\tR\x05order\"S\n" +
	"\x17ListSubmissionsResponse\x128\n" +
	"\vsubmissions\x18\x01 \x03(\v2\x16.assignment.SubmissionR\vsubmissions\"[\n" +
	"\x1dListStudentSubmissionsRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\"Z\n" +
	"\x1eListStudentSubmissionsResponse\x128\n" +
	"\vsubmissions\x18\x01 \x03(\v2\x16.assignment.SubmissionR\vsubmissions\"\x88\x01\n" +
	"\x12CreateGradeRequest\x12#\n" +
	"\rsubmission_id\x18\x01 \x01(\tR\fsubmissionId\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\x12\x1a\n" +
	"\bfeedback\x18\x03 \x01(\tR\bfeedback\x12\x1b\n" +
	"\tgraded_by\x18\x04 \x01(\tR\bgradedBy\">\n" +
	"\x13CreateGradeResponse\x12'\n" +
	"\x05grade\x18\x01 \x01(\v2\x11.assignment.GradeR\x05grade\"V\n" +
	"\x12UpdateGradeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\x12\x1a\n" +
	"\bfeedback\x18\x03 \x01(\tR\bfeedback\">\n" +
	"\x13UpdateGradeResponse\x12'\n" +
	"\x05grade\x18\x01 \x01(\v2\x11.assignment.GradeR\x05grade\"%\n" +
	"\x13PublishGradeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"?\n" +
	"\x14PublishGradeResponse\x12'\n" +
	"\x05grade\x18\x01 \x01(\v2\x11.assignment.GradeR\x05grade\"!\n" +
	"\x0fGetGradeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\";\n" +
	"\x10GetGradeResponse\x12'\n" +
	"\x05grade\x18\x01 \x01(\v2\x11.assignment.GradeR\x05grade\"X\n" +
	"\x1aGetStudentGradebookRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\"\xe3\x02\n" +
	"\x0eGradebookEntry\x12#\n" +
	"\rassignment_id\x18\x01 \x01(\tR\fassignmentId\x12)\n" +
	"\x10assignment_title\x18\x02 \x01(\tR\x0fassignmentTitle\x12\x1d\n" +
	"\n" +
	"max_points\x18\x03 \x01(\x01R\tmaxPoints\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x01R\x05score\x12%\n" +
	"\x0eadjusted_score\x18\x05 \x01(\x01R\radjustedScore\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x125\n" +
	"\bdue_date\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\adueDate\x12=\n" +
	"\fsubmitted_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vsubmittedAt\x12\x17\n" +
	"\ais_late\x18\t \x01(\bR\x06isLate\"\x9a\x02\n" +
	"\x1bGetStudentGradebookResponse\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\x124\n" +
	"\aentries\x18\x03 \x03(\v2\x1a.assignment.GradebookEntryR\aentries\x12!\n" +
	"\ftotal_points\x18\x04 \x01(\x01R\vtotalPoints\x12#\n" +
	"\rearned_points\x18\x05 \x01(\x01R\fearnedPoints\x12\x1e\n" +
	"\n" +
	"percentage\x18\x06 \x01(\x01R\n" +
	"percentage\x12!\n" +
	"\fletter_grade\x18\a \x01(\tR\vletterGrade\"8\n" +
	"\x19GetCourseGradebookRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\"\x98\x02\n" +
	"\x13StudentGradeSummary\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12!\n" +
	"\fstudent_name\x18\x02 \x01(\tR\vstudentName\x12!\n" +
	"\ftotal_points\x18\x03 \x01(\x01R\vtotalPoints\x12#\n" +
	"\rearned_points\x18\x04 \x01(\x01R\fearnedPoints\x12\x1e\n" +
	"\n" +
	"percentage\x18\x05 \x01(\x01R\n" +
	"percentage\x12!\n" +
	"\fletter_grade\x18\x06 \x01(\tR\vletterGrade\x124\n" +
	"\aentries\x18\a \x03(\v2\x1a.assignment.GradebookEntryR\aentries\"v\n" +
	"\x1aGetCourseGradebookResponse\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\x12;\n" +
	"\bstudents\x18\x02 \x03(\v2\x1f.assignment.StudentGradeSummaryR\bstudents\"@\n" +
	"\x19GetGradeStatisticsRequest\x12#\n" +
	"\rassignment_id\x18\x01 \x01(\tR\fassignmentId\"\x91\x02\n" +
	"\x0fGradeStatistics\x12#\n" +
	"\rassignment_id\x18\x01 \x01(\tR\fassignmentId\x12+\n" +
	"\x11total_submissions\x18\x02 \x01(\x05R\x10totalSubmissions\x12!\n" +
	"\fgraded_count\x18\x03 \x01(\x05R\vgradedCount\x12\x12\n" +
	"\x04mean\x18\x04 \x01(\x01R\x04mean\x12\x16\n" +
	"\x06median\x18\x05 \x01(\x01R\x06median\x12#\n" +
	"\rstd_deviation\x18\x06 \x01(\x01R\fstdDeviation\x12\x1b\n" +
	"\tmin_score\x18\a \x01(\x01R\bminScore\x12\x1b\n" +
	"\tmax_score\x18\b \x01(\x01R\bmaxScore\"Y\n" +
	"\x1aGetGradeStatisticsResponse\x12;\n" +
	"\n" +
	"statistics\x18\x01 \x01(\v2\x1b.assignment.GradeStatisticsR\n" +
	"statistics\"J\n" +
	"\x13ExportGradesRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\"B\n" +
	"\x14ExportGradesResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\"\x14\n" +
	"\x12HealthCheckRequest\"e\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp2\xb2\x04\n" +
	"\x11AssignmentService\x12]\n" +
	"\x10CreateAssignment\x12#.assignment.CreateAssignmentRequest\x1a$.assignment.CreateAssignmentResponse\x12T\n" +
	"\rGetAssignment\x12 .assignment.GetAssignmentRequest\x1a!.assignment.GetAssignmentResponse\x12]\n" +
	"\x10UpdateAssignment\x12#.assignment.UpdateAssignmentRequest\x1a$.assignment.UpdateAssignmentResponse\x12]\n" +
	"\x10DeleteAssignment\x12#.assignment.DeleteAssignmentRequest\x1a$.assignment.DeleteAssignmentResponse\x12Z\n" +
	"\x0fListAssignments\x12\".assignment.ListAssignmentsRequest\x1a#.assignment.ListAssignmentsResponse\x12N\n" +
	"\vHealthCheck\x12\x1e.assignment.HealthCheckRequest\x1a\x1f.assignment.HealthCheckResponse2\x95\x03\n" +
	"\x11SubmissionService\x12]\n" +
	"\x10SubmitAssignment\x12#.assignment.SubmitAssignmentRequest\x1a$.assignment.SubmitAssignmentResponse\x12T\n" +
	"\rGetSubmission\x12 .assignment.GetSubmissionRequest\x1a!.assignment.GetSubmissionResponse\x12Z\n" +
	"\x0fListSubmissions\x12\".assignment.ListSubmissionsRequest\x1a#.assignment.ListSubmissionsResponse\x12o\n" +
	"\x16ListStudentSubmissions\x12).assignment.ListStudentSubmissionsRequest\x1a*.assignment.ListStudentSubmissionsResponse2\xca\x02\n" +
	"\x0eGradingService\x12N\n" +
	"\vCreateGrade\x12\x1e.assignment.CreateGradeRequest\x1a\x1f.assignment.CreateGradeResponse\x12N\n" +
	"\vUpdateGrade\x12\x1e.assignment.UpdateGradeRequest\x1a\x1f.assignment.UpdateGradeResponse\x12Q\n" +
	"\fPublishGrade\x12\x1f.assignment.PublishGradeRequest\x1a .assignment.PublishGradeResponse\x12E\n" +
	"\bGetGrade\x12\x1b.assignment.GetGradeRequest\x1a\x1c.assignment.GetGradeResponse2\x97\x03\n" +
	"\x10GradebookService\x12f\n" +
	"\x13GetStudentGradebook\x12&.assignment.GetStudentGradebookRequest\x1a'.assignment.GetStudentGradebookResponse\x12c\n" +
	"\x12GetCourseGradebook\x12%.assignment.GetCourseGradebookRequest\x1a&.assignment.GetCourseGradebookResponse\x12c\n" +
	"\x12GetGradeStatistics\x12%.assignment.GetGradeStatisticsRequest\x1a&.assignment.GetGradeStatisticsResponse\x12Q\n" +
	"\fExportGrades\x12\x1f.assignment.ExportGradesRequest\x1a .assignment.ExportGradesResponseB5Z3slate/services/assignment-grading-service/api/protob\x06proto3"

var (
	file_assignment_proto_rawDescOnce sync.Once
	file_assignment_proto_rawDescData []byte
)

func file_assignment_proto_rawDescGZIP() []byte {
	file_assignment_proto_rawDescOnce.Do(func() {
		file_assignment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_assignment_proto_rawDesc), len(file_assignment_proto_rawDesc)))
	})
	return file_assignment_proto_rawDescData
}

var file_assignment_proto_msgTypes = make([]protoimpl.MessageInfo, 43)
var file_assignment_proto_goTypes = []any{
	(*LatePolicy)(nil),                     // 0: assignment.LatePolicy
	(*Assignment)(nil),                     // 1: assignment.Assignment
	(*Submission)(nil),                     // 2: assignment.Submission
	(*Grade)(nil),                          // 3: assignment.Grade
	(*CreateAssignmentRequest)(nil),        // 4: assignment.CreateAssignmentRequest
	(*CreateAssignmentResponse)(nil),       // 5: assignment.CreateAssignmentResponse
	(*GetAssignmentRequest)(nil),           // 6: assignment.GetAssignmentRequest
	(*GetAssignmentResponse)(nil),          // 7: assignment.GetAssignmentResponse
	(*UpdateAssignmentRequest)(nil),        // 8: assignment.UpdateAssignmentRequest
	(*UpdateAssignmentResponse)(nil),       // 9: assignment.UpdateAssignmentResponse
	(*DeleteAssignmentRequest)(nil),        // 10: assignment.DeleteAssignmentRequest
	(*DeleteAssignmentResponse)(nil),       // 11: assignment.DeleteAssignmentResponse
	(*ListAssignmentsRequest)(nil),         // 12: assignment.ListAssignmentsRequest
	(*ListAssignmentsResponse)(nil),        // 13: assignment.ListAssignmentsResponse
	(*SubmitAssignmentRequest)(nil),        // 14: assignment.SubmitAssignmentRequest
	(*SubmitAssignmentResponse)(nil),       // 15: assignment.SubmitAssignmentResponse
	(*GetSubmissionRequest)(nil),           // 16: assignment.GetSubmissionRequest
	(*GetSubmissionResponse)(nil),          // 17: assignment.GetSubmissionResponse
	(*ListSubmissionsRequest)(nil),         // 18: assignment.ListSubmissionsRequest
	(*ListSubmissionsResponse)(nil),        // 19: assignment.ListSubmissionsResponse
	(*ListStudentSubmissionsRequest)(nil),  // 20: assignment.ListStudentSubmissionsRequest
	(*ListStudentSubmissionsResponse)(nil), // 21: assignment.ListStudentSubmissionsResponse
	(*CreateGradeRequest)(nil),             // 22: assignment.CreateGradeRequest
	(*CreateGradeResponse)(nil),            // 23: assignment.CreateGradeResponse
	(*UpdateGradeRequest)(nil),             // 24: assignment.UpdateGradeRequest
	(*UpdateGradeResponse)(nil),            // 25: assignment.UpdateGradeResponse
	(*PublishGradeRequest)(nil),            // 26: assignment.PublishGradeRequest
	(*PublishGradeResponse)(nil),           // 27: assignment.PublishGradeResponse
	(*GetGradeRequest)(nil),                // 28: assignment.GetGradeRequest
	(*GetGradeResponse)(nil),               // 29: assignment.GetGradeResponse
	(*GetStudentGradebookRequest)(nil),     // 30: assignment.GetStudentGradebookRequest
	(*GradebookEntry)(nil),                 // 31: assignment.GradebookEntry
	(*GetStudentGradebookResponse)(nil),    // 32: assignment.GetStudentGradebookResponse
	(*GetCourseGradebookRequest)(nil),      // 33: assignment.GetCourseGradebookRequest
	(*StudentGradeSummary)(nil),            // 34: assignment.StudentGradeSummary
	(*GetCourseGradebookResponse)(nil),     // 35: assignment.GetCourseGradebookResponse
	(*GetGradeStatisticsRequest)(nil),      // 36: assignment.GetGradeStatisticsRequest
	(*GradeStatistics)(nil),                // 37: assignment.GradeStatistics
	(*GetGradeStatisticsResponse)(nil),     // 38: assignment.GetGradeStatisticsResponse
	(*ExportGradesRequest)(nil),            // 39: assignment.ExportGradesRequest
	(*ExportGradesResponse)(nil),           // 40: assignment.ExportGradesResponse
	(*HealthCheckRequest)(nil),             // 41: assignment.HealthCheckRequest
	(*HealthCheckResponse)(nil),            // 42: assignment.HealthCheckResponse
	(*timestamppb.Timestamp)(nil),          // 43: google.protobuf.Timestamp
}
var file_assignment_proto_depIdxs = []int32{
	43, // 0: assignment.Assignment.due_date:type_name -> google.protobuf.Timestamp
	0,  // 1: assignment.Assignment.late_policy:type_name -> assignment.LatePolicy
	43, // 2: assignment.Assignment.created_at:type_name -> google.protobuf.Timestamp
	43, // 3: assignment.Assignment.updated_at:type_name -> google.protobuf.Timestamp
	43, // 4: assignment.Submission.submitted_at:type_name -> google.protobuf.Timestamp
	43, // 5: assignment.Submission.created_at:type_name -> google.protobuf.Timestamp
	43, // 6: assignment.Submission.updated_at:type_name -> google.protobuf.Timestamp
	43, // 7: assignment.Grade.graded_at:type_name -> google.protobuf.Timestamp
	43, // 8: assignment.Grade.published_at:type_name -> google.protobuf.Timestamp
	43, // 9: assignment.Grade.created_at:type_name -> google.protobuf.Timestamp
	43, // 10: assignment.Grade.updated_at:type_name -> google.protobuf.Timestamp
	43, // 11: assignment.CreateAssignmentRequest.due_date:type_name -> google.protobuf.Timestamp
	0,  // 12: assignment.CreateAssignmentRequest.late_policy:type_name -> assignment.LatePolicy
	1,  // 13: assignment.CreateAssignmentResponse.assignment:type_name -> assignment.Assignment
	1,  // 14: assignment.GetAssignmentResponse.assignment:type_name -> assignment.Assignment
	43, // 15: assignment.UpdateAssignmentRequest.due_date:type_name -> google.protobuf.Timestamp
	0,  // 16: assignment.UpdateAssignmentRequest.late_policy:type_name -> assignment.LatePolicy
	1,  // 17: assignment.UpdateAssignmentResponse.assignment:type_name -> assignment.Assignment
	1,  // 18: assignment.ListAssignmentsResponse.assignments:type_name -> assignment.Assignment
	2,  // 19: assignment.SubmitAssignmentResponse.submission:type_name -> assignment.Submission
	2,  // 20: assignment.GetSubmissionResponse.submission:type_name -> assignment.Submission
	2,  // 21: assignment.ListSubmissionsResponse.submissions:type_name -> assignment.Submission
	2,  // 22: assignment.ListStudentSubmissionsResponse.submissions:type_name -> assignment.Submission
	3,  // 23: assignment.CreateGradeResponse.grade:type_name -> assignment.Grade
	3,  // 24: assignment.UpdateGradeResponse.grade:type_name -> assignment.Grade
	3,  // 25: assignment.PublishGradeResponse.grade:type_name -> assignment.Grade
	3,  // 26: assignment.GetGradeResponse.grade:type_name -> assignment.Grade
	43, // 27: assignment.GradebookEntry.due_date:type_name -> google.protobuf.Timestamp
	43, // 28: assignment.GradebookEntry.submitted_at:type_name -> google.protobuf.Timestamp
	31, // 29: assignment.GetStudentGradebookResponse.entries:type_name -> assignment.GradebookEntry
	31, // 30: assignment.StudentGradeSummary.entries:type_name -> assignment.GradebookEntry
	34, // 31: assignment.GetCourseGradebookResponse.students:type_name -> assignment.StudentGradeSummary
	37, // 32: assignment.GetGradeStatisticsResponse.statistics:type_name -> assignment.GradeStatistics
	4,  // 33: assignment.AssignmentService.CreateAssignment:input_type -> assignment.CreateAssignmentRequest
	6,  // 34: assignment.AssignmentService.GetAssignment:input_type -> assignment.GetAssignmentRequest
	8,  // 35: assignment.AssignmentService.UpdateAssignment:input_type -> assignment.UpdateAssignmentRequest
	10, // 36: assignment.AssignmentService.DeleteAssignment:input_type -> assignment.DeleteAssignmentRequest
	12, // 37: assignment.AssignmentService.ListAssignments:input_type -> assignment.ListAssignmentsRequest
	41, // 38: assignment.AssignmentService.HealthCheck:input_type -> assignment.HealthCheckRequest
	14, // 39: assignment.SubmissionService.SubmitAssignment:input_type -> assignment.SubmitAssignmentRequest
	16, // 40: assignment.SubmissionService.GetSubmission:input_type -> assignment.GetSubmissionRequest
	18, // 41: assignment.SubmissionService.ListSubmissions:input_type -> assignment.ListSubmissionsRequest
	20, // 42: assignment.SubmissionService.ListStudentSubmissions:input_type -> assignment.ListStudentSubmissionsRequest
	22, // 43: assignment.GradingService.CreateGrade:input_type -> assignment.CreateGradeRequest
	24, // 44: assignment.GradingService.UpdateGrade:input_type -> assignment.UpdateGradeRequest
	26, // 45: assignment.GradingService.PublishGrade:input_type -> assignment.PublishGradeRequest
	28, // 46: assignment.GradingService.GetGrade:input_type -> assignment.GetGradeRequest
	30, // 47: assignment.GradebookService.GetStudentGradebook:input_type -> assignment.GetStudentGradebookRequest
	33, // 48: assignment.GradebookService.GetCourseGradebook:input_type -> assignment.GetCourseGradebookRequest
	36, // 49: assignment.GradebookService.GetGradeStatistics:input_type -> assignment.GetGradeStatisticsRequest
	39, // 50: assignment.GradebookService.ExportGrades:input_type -> assignment.ExportGradesRequest
	5,  // 51: assignment.AssignmentService.CreateAssignment:output_type -> assignment.CreateAssignmentResponse
	7,  // 52: assignment.AssignmentService.GetAssignment:output_type -> assignment.GetAssignmentResponse
	9,  // 53: assignment.AssignmentService.UpdateAssignment:output_type -> assignment.UpdateAssignmentResponse
	11, // 54: assignment.AssignmentService.DeleteAssignment:output_type -> assignment.DeleteAssignmentResponse
	13, // 55: assignment.AssignmentService.ListAssignments:output_type -> assignment.ListAssignmentsResponse
	42, // 56: assignment.AssignmentService.HealthCheck:output_type -> assignment.HealthCheckResponse
	15, // 57: assignment.SubmissionService.SubmitAssignment:output_type -> assignment.SubmitAssignmentResponse
	17, // 58: assignment.SubmissionService.GetSubmission:output_type -> assignment.GetSubmissionResponse
	19, // 59: assignment.SubmissionService.ListSubmissions:output_type -> assignment.ListSubmissionsResponse
	21, // 60: assignment.SubmissionService.ListStudentSubmissions:output_type -> assignment.ListStudentSubmissionsResponse
	23, // 61: assignment.GradingService.CreateGrade:output_type -> assignment.CreateGradeResponse
	25, // 62: assignment.GradingService.UpdateGrade:output_type -> assignment.UpdateGradeResponse
	27, // 63: assignment.GradingService.PublishGrade:output_type -> assignment.PublishGradeResponse
	29, // 64: assignment.GradingService.GetGrade:output_type -> assignment.GetGradeResponse
	32, // 65: assignment.GradebookService.GetStudentGradebook:output_type -> assignment.GetStudentGradebookResponse
	35, // 66: assignment.GradebookService.GetCourseGradebook:output_type -> assignment.GetCourseGradebookResponse
	38, // 67: assignment.GradebookService.GetGradeStatistics:output_type -> assignment.GetGradeStatisticsResponse
	40, // 68: assignment.GradebookService.ExportGrades:output_type -> assignment.ExportGradesResponse
	51, // [51:69] is the sub-list for method output_type
	33, // [33:51] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_assignment_proto_init() }
func file_assignment_proto_init() {
	if File_assignment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_assignment_proto_rawDesc), len(file_assignment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   43,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_assignment_proto_goTypes,
		DependencyIndexes: file_assignment_proto_depIdxs,
		MessageInfos:      file_assignment_proto_msgTypes,
	}.Build()
	File_assignment_proto = out.File
	file_assignment_proto_goTypes = nil
	file_assignment_proto_depIdxs = nil
}
