// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: assignment.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AssignmentService_CreateAssignment_FullMethodName = "/assignment.AssignmentService/CreateAssignment"
	AssignmentService_GetAssignment_FullMethodName    = "/assignment.AssignmentService/GetAssignment"
	AssignmentService_UpdateAssignment_FullMethodName = "/assignment.AssignmentService/UpdateAssignment"
	AssignmentService_DeleteAssignment_FullMethodName = "/assignment.AssignmentService/DeleteAssignment"
	AssignmentService_ListAssignments_FullMethodName  = "/assignment.AssignmentService/ListAssignments"
	AssignmentService_HealthCheck_FullMethodName      = "/assignment.AssignmentService/HealthCheck"
)

// AssignmentServiceClient is the client API for AssignmentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Assignment Service - manages assignment CRUD operations
type AssignmentServiceClient interface {
	CreateAssignment(ctx context.Context, in *CreateAssignmentRequest, opts ...grpc.CallOption) (*CreateAssignmentResponse, error)
	GetAssignment(ctx context.Context, in *GetAssignmentRequest, opts ...grpc.CallOption) (*GetAssignmentResponse, error)
	UpdateAssignment(ctx context.Context, in *UpdateAssignmentRequest, opts ...grpc.CallOption) (*UpdateAssignmentResponse, error)
	DeleteAssignment(ctx context.Context, in *DeleteAssignmentRequest, opts ...grpc.CallOption) (*DeleteAssignmentResponse, error)
	ListAssignments(ctx context.Context, in *ListAssignmentsRequest, opts ...grpc.CallOption) (*ListAssignmentsResponse, error)
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type assignmentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAssignmentServiceClient(cc grpc.ClientConnInterface) AssignmentServiceClient {
	return &assignmentServiceClient{cc}
}

func (c *assignmentServiceClient) CreateAssignment(ctx context.Context, in *CreateAssignmentRequest, opts ...grpc.CallOption) (*CreateAssignmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAssignmentResponse)
	err := c.cc.Invoke(ctx, AssignmentService_CreateAssignment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assignmentServiceClient) GetAssignment(ctx context.Context, in *GetAssignmentRequest, opts ...grpc.CallOption) (*GetAssignmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAssignmentResponse)
	err := c.cc.Invoke(ctx, AssignmentService_GetAssignment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assignmentServiceClient) UpdateAssignment(ctx context.Context, in *UpdateAssignmentRequest, opts ...grpc.CallOption) (*UpdateAssignmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAssignmentResponse)
	err := c.cc.Invoke(ctx, AssignmentService_UpdateAssignment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assignmentServiceClient) DeleteAssignment(ctx context.Context, in *DeleteAssignmentRequest, opts ...grpc.CallOption) (*DeleteAssignmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAssignmentResponse)
	err := c.cc.Invoke(ctx, AssignmentService_DeleteAssignment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assignmentServiceClient) ListAssignments(ctx context.Context, in *ListAssignmentsRequest, opts ...grpc.CallOption) (*ListAssignmentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAssignmentsResponse)
	err := c.cc.Invoke(ctx, AssignmentService_ListAssignments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assignmentServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, AssignmentService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AssignmentServiceServer is the server API for AssignmentService service.
// All implementations must embed UnimplementedAssignmentServiceServer
// for forward compatibility.
//
// Assignment Service - manages assignment CRUD operations
type AssignmentServiceServer interface {
	CreateAssignment(context.Context, *CreateAssignmentRequest) (*CreateAssignmentResponse, error)
	GetAssignment(context.Context, *GetAssignmentRequest) (*GetAssignmentResponse, error)
	UpdateAssignment(context.Context, *UpdateAssignmentRequest) (*UpdateAssignmentResponse, error)
	DeleteAssignment(context.Context, *DeleteAssignmentRequest) (*DeleteAssignmentResponse, error)
	ListAssignments(context.Context, *ListAssignmentsRequest) (*ListAssignmentsResponse, error)
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedAssignmentServiceServer()
}

// UnimplementedAssignmentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAssignmentServiceServer struct{}

func (UnimplementedAssignmentServiceServer) CreateAssignment(context.Context, *CreateAssignmentRequest) (*CreateAssignmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAssignment not implemented")
}
func (UnimplementedAssignmentServiceServer) GetAssignment(context.Context, *GetAssignmentRequest) (*GetAssignmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAssignment not implemented")
}
func (UnimplementedAssignmentServiceServer) UpdateAssignment(context.Context, *UpdateAssignmentRequest) (*UpdateAssignmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAssignment not implemented")
}
func (UnimplementedAssignmentServiceServer) DeleteAssignment(context.Context, *DeleteAssignmentRequest) (*DeleteAssignmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAssignment not implemented")
}
func (UnimplementedAssignmentServiceServer) ListAssignments(context.Context, *ListAssignmentsRequest) (*ListAssignmentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAssignments not implemented")
}
func (UnimplementedAssignmentServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedAssignmentServiceServer) mustEmbedUnimplementedAssignmentServiceServer() {}
func (UnimplementedAssignmentServiceServer) testEmbeddedByValue()                           {}

// UnsafeAssignmentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AssignmentServiceServer will
// result in compilation errors.
type UnsafeAssignmentServiceServer interface {
	mustEmbedUnimplementedAssignmentServiceServer()
}

func RegisterAssignmentServiceServer(s grpc.ServiceRegistrar, srv AssignmentServiceServer) {
	// If the following call pancis, it indicates UnimplementedAssignmentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AssignmentService_ServiceDesc, srv)
}

func _AssignmentService_CreateAssignment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAssignmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssignmentServiceServer).CreateAssignment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssignmentService_CreateAssignment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssignmentServiceServer).CreateAssignment(ctx, req.(*CreateAssignmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssignmentService_GetAssignment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAssignmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssignmentServiceServer).GetAssignment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssignmentService_GetAssignment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssignmentServiceServer).GetAssignment(ctx, req.(*GetAssignmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssignmentService_UpdateAssignment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAssignmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssignmentServiceServer).UpdateAssignment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssignmentService_UpdateAssignment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssignmentServiceServer).UpdateAssignment(ctx, req.(*UpdateAssignmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssignmentService_DeleteAssignment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAssignmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssignmentServiceServer).DeleteAssignment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssignmentService_DeleteAssignment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssignmentServiceServer).DeleteAssignment(ctx, req.(*DeleteAssignmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssignmentService_ListAssignments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAssignmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssignmentServiceServer).ListAssignments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssignmentService_ListAssignments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssignmentServiceServer).ListAssignments(ctx, req.(*ListAssignmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssignmentService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssignmentServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssignmentService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssignmentServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AssignmentService_ServiceDesc is the grpc.ServiceDesc for AssignmentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AssignmentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "assignment.AssignmentService",
	HandlerType: (*AssignmentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAssignment",
			Handler:    _AssignmentService_CreateAssignment_Handler,
		},
		{
			MethodName: "GetAssignment",
			Handler:    _AssignmentService_GetAssignment_Handler,
		},
		{
			MethodName: "UpdateAssignment",
			Handler:    _AssignmentService_UpdateAssignment_Handler,
		},
		{
			MethodName: "DeleteAssignment",
			Handler:    _AssignmentService_DeleteAssignment_Handler,
		},
		{
			MethodName: "ListAssignments",
			Handler:    _AssignmentService_ListAssignments_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _AssignmentService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "assignment.proto",
}

const (
	SubmissionService_SubmitAssignment_FullMethodName       = "/assignment.SubmissionService/SubmitAssignment"
	SubmissionService_GetSubmission_FullMethodName          = "/assignment.SubmissionService/GetSubmission"
	SubmissionService_ListSubmissions_FullMethodName        = "/assignment.SubmissionService/ListSubmissions"
	SubmissionService_ListStudentSubmissions_FullMethodName = "/assignment.SubmissionService/ListStudentSubmissions"
)

// SubmissionServiceClient is the client API for SubmissionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Submission Service - manages assignment submissions
type SubmissionServiceClient interface {
	SubmitAssignment(ctx context.Context, in *SubmitAssignmentRequest, opts ...grpc.CallOption) (*SubmitAssignmentResponse, error)
	GetSubmission(ctx context.Context, in *GetSubmissionRequest, opts ...grpc.CallOption) (*GetSubmissionResponse, error)
	ListSubmissions(ctx context.Context, in *ListSubmissionsRequest, opts ...grpc.CallOption) (*ListSubmissionsResponse, error)
	ListStudentSubmissions(ctx context.Context, in *ListStudentSubmissionsRequest, opts ...grpc.CallOption) (*ListStudentSubmissionsResponse, error)
}

type submissionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSubmissionServiceClient(cc grpc.ClientConnInterface) SubmissionServiceClient {
	return &submissionServiceClient{cc}
}

func (c *submissionServiceClient) SubmitAssignment(ctx context.Context, in *SubmitAssignmentRequest, opts ...grpc.CallOption) (*SubmitAssignmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitAssignmentResponse)
	err := c.cc.Invoke(ctx, SubmissionService_SubmitAssignment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *submissionServiceClient) GetSubmission(ctx context.Context, in *GetSubmissionRequest, opts ...grpc.CallOption) (*GetSubmissionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSubmissionResponse)
	err := c.cc.Invoke(ctx, SubmissionService_GetSubmission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *submissionServiceClient) ListSubmissions(ctx context.Context, in *ListSubmissionsRequest, opts ...grpc.CallOption) (*ListSubmissionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSubmissionsResponse)
	err := c.cc.Invoke(ctx, SubmissionService_ListSubmissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *submissionServiceClient) ListStudentSubmissions(ctx context.Context, in *ListStudentSubmissionsRequest, opts ...grpc.CallOption) (*ListStudentSubmissionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListStudentSubmissionsResponse)
	err := c.cc.Invoke(ctx, SubmissionService_ListStudentSubmissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubmissionServiceServer is the server API for SubmissionService service.
// All implementations must embed UnimplementedSubmissionServiceServer
// for forward compatibility.
//
// Submission Service - manages assignment submissions
type SubmissionServiceServer interface {
	SubmitAssignment(context.Context, *SubmitAssignmentRequest) (*SubmitAssignmentResponse, error)
	GetSubmission(context.Context, *GetSubmissionRequest) (*GetSubmissionResponse, error)
	ListSubmissions(context.Context, *ListSubmissionsRequest) (*ListSubmissionsResponse, error)
	ListStudentSubmissions(context.Context, *ListStudentSubmissionsRequest) (*ListStudentSubmissionsResponse, error)
	mustEmbedUnimplementedSubmissionServiceServer()
}

// UnimplementedSubmissionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSubmissionServiceServer struct{}

func (UnimplementedSubmissionServiceServer) SubmitAssignment(context.Context, *SubmitAssignmentRequest) (*SubmitAssignmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitAssignment not implemented")
}
func (UnimplementedSubmissionServiceServer) GetSubmission(context.Context, *GetSubmissionRequest) (*GetSubmissionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSubmission not implemented")
}
func (UnimplementedSubmissionServiceServer) ListSubmissions(context.Context, *ListSubmissionsRequest) (*ListSubmissionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSubmissions not implemented")
}
func (UnimplementedSubmissionServiceServer) ListStudentSubmissions(context.Context, *ListStudentSubmissionsRequest) (*ListStudentSubmissionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListStudentSubmissions not implemented")
}
func (UnimplementedSubmissionServiceServer) mustEmbedUnimplementedSubmissionServiceServer() {}
func (UnimplementedSubmissionServiceServer) testEmbeddedByValue()                           {}

// UnsafeSubmissionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SubmissionServiceServer will
// result in compilation errors.
type UnsafeSubmissionServiceServer interface {
	mustEmbedUnimplementedSubmissionServiceServer()
}

func RegisterSubmissionServiceServer(s grpc.ServiceRegistrar, srv SubmissionServiceServer) {
	// If the following call pancis, it indicates UnimplementedSubmissionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SubmissionService_ServiceDesc, srv)
}

func _SubmissionService_SubmitAssignment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitAssignmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubmissionServiceServer).SubmitAssignment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubmissionService_SubmitAssignment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubmissionServiceServer).SubmitAssignment(ctx, req.(*SubmitAssignmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubmissionService_GetSubmission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSubmissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubmissionServiceServer).GetSubmission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubmissionService_GetSubmission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubmissionServiceServer).GetSubmission(ctx, req.(*GetSubmissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubmissionService_ListSubmissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSubmissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubmissionServiceServer).ListSubmissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubmissionService_ListSubmissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubmissionServiceServer).ListSubmissions(ctx, req.(*ListSubmissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubmissionService_ListStudentSubmissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStudentSubmissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubmissionServiceServer).ListStudentSubmissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubmissionService_ListStudentSubmissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubmissionServiceServer).ListStudentSubmissions(ctx, req.(*ListStudentSubmissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SubmissionService_ServiceDesc is the grpc.ServiceDesc for SubmissionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SubmissionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "assignment.SubmissionService",
	HandlerType: (*SubmissionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitAssignment",
			Handler:    _SubmissionService_SubmitAssignment_Handler,
		},
		{
			MethodName: "GetSubmission",
			Handler:    _SubmissionService_GetSubmission_Handler,
		},
		{
			MethodName: "ListSubmissions",
			Handler:    _SubmissionService_ListSubmissions_Handler,
		},
		{
			MethodName: "ListStudentSubmissions",
			Handler:    _SubmissionService_ListStudentSubmissions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "assignment.proto",
}

const (
	GradingService_CreateGrade_FullMethodName  = "/assignment.GradingService/CreateGrade"
	GradingService_UpdateGrade_FullMethodName  = "/assignment.GradingService/UpdateGrade"
	GradingService_PublishGrade_FullMethodName = "/assignment.GradingService/PublishGrade"
	GradingService_GetGrade_FullMethodName     = "/assignment.GradingService/GetGrade"
)

// GradingServiceClient is the client API for GradingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Grading Service - manages grade creation and publishing
type GradingServiceClient interface {
	CreateGrade(ctx context.Context, in *CreateGradeRequest, opts ...grpc.CallOption) (*CreateGradeResponse, error)
	UpdateGrade(ctx context.Context, in *UpdateGradeRequest, opts ...grpc.CallOption) (*UpdateGradeResponse, error)
	PublishGrade(ctx context.Context, in *PublishGradeRequest, opts ...grpc.CallOption) (*PublishGradeResponse, error)
	GetGrade(ctx context.Context, in *GetGradeRequest, opts ...grpc.CallOption) (*GetGradeResponse, error)
}

type gradingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGradingServiceClient(cc grpc.ClientConnInterface) GradingServiceClient {
	return &gradingServiceClient{cc}
}

func (c *gradingServiceClient) CreateGrade(ctx context.Context, in *CreateGradeRequest, opts ...grpc.CallOption) (*CreateGradeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateGradeResponse)
	err := c.cc.Invoke(ctx, GradingService_CreateGrade_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gradingServiceClient) UpdateGrade(ctx context.Context, in *UpdateGradeRequest, opts ...grpc.CallOption) (*UpdateGradeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateGradeResponse)
	err := c.cc.Invoke(ctx, GradingService_UpdateGrade_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gradingServiceClient) PublishGrade(ctx context.Context, in *PublishGradeRequest, opts ...grpc.CallOption) (*PublishGradeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishGradeResponse)
	err := c.cc.Invoke(ctx, GradingService_PublishGrade_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gradingServiceClient) GetGrade(ctx context.Context, in *GetGradeRequest, opts ...grpc.CallOption) (*GetGradeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGradeResponse)
	err := c.cc.Invoke(ctx, GradingService_GetGrade_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GradingServiceServer is the server API for GradingService service.
// All implementations must embed UnimplementedGradingServiceServer
// for forward compatibility.
//
// Grading Service - manages grade creation and publishing
type GradingServiceServer interface {
	CreateGrade(context.Context, *CreateGradeRequest) (*CreateGradeResponse, error)
	UpdateGrade(context.Context, *UpdateGradeRequest) (*UpdateGradeResponse, error)
	PublishGrade(context.Context, *PublishGradeRequest) (*PublishGradeResponse, error)
	GetGrade(context.Context, *GetGradeRequest) (*GetGradeResponse, error)
	mustEmbedUnimplementedGradingServiceServer()
}

// UnimplementedGradingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGradingServiceServer struct{}

func (UnimplementedGradingServiceServer) CreateGrade(context.Context, *CreateGradeRequest) (*CreateGradeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGrade not implemented")
}
func (UnimplementedGradingServiceServer) UpdateGrade(context.Context, *UpdateGradeRequest) (*UpdateGradeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateGrade not implemented")
}
func (UnimplementedGradingServiceServer) PublishGrade(context.Context, *PublishGradeRequest) (*PublishGradeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishGrade not implemented")
}
func (UnimplementedGradingServiceServer) GetGrade(context.Context, *GetGradeRequest) (*GetGradeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGrade not implemented")
}
func (UnimplementedGradingServiceServer) mustEmbedUnimplementedGradingServiceServer() {}
func (UnimplementedGradingServiceServer) testEmbeddedByValue()                        {}

// UnsafeGradingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GradingServiceServer will
// result in compilation errors.
type UnsafeGradingServiceServer interface {
	mustEmbedUnimplementedGradingServiceServer()
}

func RegisterGradingServiceServer(s grpc.ServiceRegistrar, srv GradingServiceServer) {
	// If the following call pancis, it indicates UnimplementedGradingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GradingService_ServiceDesc, srv)
}

func _GradingService_CreateGrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GradingServiceServer).CreateGrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GradingService_CreateGrade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GradingServiceServer).CreateGrade(ctx, req.(*CreateGradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GradingService_UpdateGrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GradingServiceServer).UpdateGrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GradingService_UpdateGrade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GradingServiceServer).UpdateGrade(ctx, req.(*UpdateGradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GradingService_PublishGrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishGradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GradingServiceServer).PublishGrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GradingService_PublishGrade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GradingServiceServer).PublishGrade(ctx, req.(*PublishGradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GradingService_GetGrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GradingServiceServer).GetGrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GradingService_GetGrade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GradingServiceServer).GetGrade(ctx, req.(*GetGradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GradingService_ServiceDesc is the grpc.ServiceDesc for GradingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GradingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "assignment.GradingService",
	HandlerType: (*GradingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateGrade",
			Handler:    _GradingService_CreateGrade_Handler,
		},
		{
			MethodName: "UpdateGrade",
			Handler:    _GradingService_UpdateGrade_Handler,
		},
		{
			MethodName: "PublishGrade",
			Handler:    _GradingService_PublishGrade_Handler,
		},
		{
			MethodName: "GetGrade",
			Handler:    _GradingService_GetGrade_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "assignment.proto",
}

const (
	GradebookService_GetStudentGradebook_FullMethodName = "/assignment.GradebookService/GetStudentGradebook"
	GradebookService_GetCourseGradebook_FullMethodName  = "/assignment.GradebookService/GetCourseGradebook"
	GradebookService_GetGradeStatistics_FullMethodName  = "/assignment.GradebookService/GetGradeStatistics"
	GradebookService_ExportGrades_FullMethodName        = "/assignment.GradebookService/ExportGrades"
)

// GradebookServiceClient is the client API for GradebookService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Gradebook Service - provides gradebook views and statistics
type GradebookServiceClient interface {
	GetStudentGradebook(ctx context.Context, in *GetStudentGradebookRequest, opts ...grpc.CallOption) (*GetStudentGradebookResponse, error)
	GetCourseGradebook(ctx context.Context, in *GetCourseGradebookRequest, opts ...grpc.CallOption) (*GetCourseGradebookResponse, error)
	GetGradeStatistics(ctx context.Context, in *GetGradeStatisticsRequest, opts ...grpc.CallOption) (*GetGradeStatisticsResponse, error)
	ExportGrades(ctx context.Context, in *ExportGradesRequest, opts ...grpc.CallOption) (*ExportGradesResponse, error)
}

type gradebookServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGradebookServiceClient(cc grpc.ClientConnInterface) GradebookServiceClient {
	return &gradebookServiceClient{cc}
}

func (c *gradebookServiceClient) GetStudentGradebook(ctx context.Context, in *GetStudentGradebookRequest, opts ...grpc.CallOption) (*GetStudentGradebookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStudentGradebookResponse)
	err := c.cc.Invoke(ctx, GradebookService_GetStudentGradebook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gradebookServiceClient) GetCourseGradebook(ctx context.Context, in *GetCourseGradebookRequest, opts ...grpc.CallOption) (*GetCourseGradebookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCourseGradebookResponse)
	err := c.cc.Invoke(ctx, GradebookService_GetCourseGradebook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gradebookServiceClient) GetGradeStatistics(ctx context.Context, in *GetGradeStatisticsRequest, opts ...grpc.CallOption) (*GetGradeStatisticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGradeStatisticsResponse)
	err := c.cc.Invoke(ctx, GradebookService_GetGradeStatistics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gradebookServiceClient) ExportGrades(ctx context.Context, in *ExportGradesRequest, opts ...grpc.CallOption) (*ExportGradesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportGradesResponse)
	err := c.cc.Invoke(ctx, GradebookService_ExportGrades_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GradebookServiceServer is the server API for GradebookService service.
// All implementations must embed UnimplementedGradebookServiceServer
// for forward compatibility.
//
// Gradebook Service - provides gradebook views and statistics
type GradebookServiceServer interface {
	GetStudentGradebook(context.Context, *GetStudentGradebookRequest) (*GetStudentGradebookResponse, error)
	GetCourseGradebook(context.Context, *GetCourseGradebookRequest) (*GetCourseGradebookResponse, error)
	GetGradeStatistics(context.Context, *GetGradeStatisticsRequest) (*GetGradeStatisticsResponse, error)
	ExportGrades(context.Context, *ExportGradesRequest) (*ExportGradesResponse, error)
	mustEmbedUnimplementedGradebookServiceServer()
}

// UnimplementedGradebookServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGradebookServiceServer struct{}

func (UnimplementedGradebookServiceServer) GetStudentGradebook(context.Context, *GetStudentGradebookRequest) (*GetStudentGradebookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStudentGradebook not implemented")
}
func (UnimplementedGradebookServiceServer) GetCourseGradebook(context.Context, *GetCourseGradebookRequest) (*GetCourseGradebookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCourseGradebook not implemented")
}
func (UnimplementedGradebookServiceServer) GetGradeStatistics(context.Context, *GetGradeStatisticsRequest) (*GetGradeStatisticsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGradeStatistics not implemented")
}
func (UnimplementedGradebookServiceServer) ExportGrades(context.Context, *ExportGradesRequest) (*ExportGradesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExportGrades not implemented")
}
func (UnimplementedGradebookServiceServer) mustEmbedUnimplementedGradebookServiceServer() {}
func (UnimplementedGradebookServiceServer) testEmbeddedByValue()                          {}

// UnsafeGradebookServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GradebookServiceServer will
// result in compilation errors.
type UnsafeGradebookServiceServer interface {
	mustEmbedUnimplementedGradebookServiceServer()
}

func RegisterGradebookServiceServer(s grpc.ServiceRegistrar, srv GradebookServiceServer) {
	// If the following call pancis, it indicates UnimplementedGradebookServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GradebookService_ServiceDesc, srv)
}

func _GradebookService_GetStudentGradebook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStudentGradebookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GradebookServiceServer).GetStudentGradebook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GradebookService_GetStudentGradebook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GradebookServiceServer).GetStudentGradebook(ctx, req.(*GetStudentGradebookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GradebookService_GetCourseGradebook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCourseGradebookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GradebookServiceServer).GetCourseGradebook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GradebookService_GetCourseGradebook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GradebookServiceServer).GetCourseGradebook(ctx, req.(*GetCourseGradebookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GradebookService_GetGradeStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGradeStatisticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GradebookServiceServer).GetGradeStatistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GradebookService_GetGradeStatistics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GradebookServiceServer).GetGradeStatistics(ctx, req.(*GetGradeStatisticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GradebookService_ExportGrades_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportGradesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GradebookServiceServer).ExportGrades(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GradebookService_ExportGrades_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GradebookServiceServer).ExportGrades(ctx, req.(*ExportGradesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GradebookService_ServiceDesc is the grpc.ServiceDesc for GradebookService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GradebookService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "assignment.GradebookService",
	HandlerType: (*GradebookServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStudentGradebook",
			Handler:    _GradebookService_GetStudentGradebook_Handler,
		},
		{
			MethodName: "GetCourseGradebook",
			Handler:    _GradebookService_GetCourseGradebook_Handler,
		},
		{
			MethodName: "GetGradeStatistics",
			Handler:    _GradebookService_GetGradeStatistics_Handler,
		},
		{
			MethodName: "ExportGrades",
			Handler:    _GradebookService_ExportGrades_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "assignment.proto",
}
