pub mod auth;
pub mod config;
pub mod discovery;
pub mod docs;
pub mod grpc;
pub mod handlers;
pub mod health;
pub mod middleware;
pub mod observability;
pub mod proto;
mod response;
pub mod router;
pub mod security;
pub mod shared;
