// Extend existing mock data with new features

// Video Conferencing
export const mockVideoRooms = [
  {
    id: 'room-1',
    name: 'CS 101 - Office Hours',
    courseId: '1',
    courseName: 'CS 101',
    hostName: 'Dr. Sarah Smith',
    hostAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    isActive: true,
    participants: 8,
    maxParticipants: 50,
    startTime: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    endTime: new Date(Date.now() + 30 * 60 * 1000).toISOString(),
    recordingEnabled: true,
    chatEnabled: true,
  },
  {
    id: 'room-2',
    name: 'MATH 201 - Study Session',
    courseId: '2',
    courseName: 'MATH 201',
    hostName: 'Study Group Alpha',
    hostAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Group',
    isActive: false,
    participants: 0,
    maxParticipants: 20,
    startTime: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
    endTime: new Date(Date.now() + 3 * 60 * 60 * 1000).toISOString(),
    recordingEnabled: false,
    chatEnabled: true,
  },
];

// File Management
export const mockFiles = [
  {
    id: 'file-1',
    name: 'Data Structures Project.py',
    type: 'python',
    size: 15432,
    courseId: '1',
    courseName: 'CS 101',
    folderId: 'folder-1',
    uploadedAt: '2024-11-10T10:30:00Z',
    modifiedAt: '2024-11-15T14:20:00Z',
    url: '/files/data-structures.py',
    isShared: false,
  },
  {
    id: 'file-2',
    name: 'Calculus Notes.pdf',
    type: 'pdf',
    size: 2457600,
    courseId: '2',
    courseName: 'MATH 201',
    folderId: 'folder-2',
    uploadedAt: '2024-11-08T09:15:00Z',
    modifiedAt: '2024-11-08T09:15:00Z',
    url: '/files/calculus-notes.pdf',
    isShared: true,
  },
  {
    id: 'file-3',
    name: 'Essay Draft.docx',
    type: 'document',
    size: 45678,
    courseId: '3',
    courseName: 'ENG 102',
    folderId: 'folder-3',
    uploadedAt: '2024-11-12T16:45:00Z',
    modifiedAt: '2024-11-14T11:30:00Z',
    url: '/files/essay-draft.docx',
    isShared: false,
  },
  {
    id: 'file-4',
    name: 'Lab Report.pdf',
    type: 'pdf',
    size: 1234567,
    courseId: '4',
    courseName: 'PHY 201',
    folderId: 'folder-4',
    uploadedAt: '2024-11-13T13:20:00Z',
    modifiedAt: '2024-11-13T13:20:00Z',
    url: '/files/lab-report.pdf',
    isShared: true,
  },
];

export const mockFolders = [
  { id: 'folder-1', name: 'CS 101', courseId: '1', fileCount: 12, size: 45678900 },
  { id: 'folder-2', name: 'MATH 201', courseId: '2', fileCount: 8, size: 23456789 },
  { id: 'folder-3', name: 'ENG 102', courseId: '3', fileCount: 15, size: 67891234 },
  { id: 'folder-4', name: 'PHY 201', courseId: '4', fileCount: 10, size: 34567890 },
];

// Study Groups
export const mockStudyGroups = [
  {
    id: 'group-1',
    name: 'CS 101 - Algorithms Study Group',
    courseId: '1',
    courseName: 'CS 101',
    description: 'Weekly study sessions focusing on algorithms and data structures',
    members: 12,
    maxMembers: 15,
    meetingSchedule: 'Thursdays 6:00 PM',
    location: 'Library Room 203',
    isPrivate: false,
    tags: ['algorithms', 'python', 'data-structures'],
    createdBy: 'Alice Johnson',
    createdAt: '2024-09-15T00:00:00Z',
    nextMeeting: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'group-2',
    name: 'Math Warriors',
    courseId: '2',
    courseName: 'MATH 201',
    description: 'Collaborative problem-solving for calculus',
    members: 8,
    maxMembers: 10,
    meetingSchedule: 'Tuesdays & Fridays 4:00 PM',
    location: 'Virtual (Zoom)',
    isPrivate: false,
    tags: ['calculus', 'integration', 'derivatives'],
    createdBy: 'Bob Smith',
    createdAt: '2024-09-20T00:00:00Z',
    nextMeeting: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'group-3',
    name: 'Writing Circle',
    courseId: '3',
    courseName: 'ENG 102',
    description: 'Peer review and writing workshops',
    members: 6,
    maxMembers: 8,
    meetingSchedule: 'Wednesdays 3:00 PM',
    location: 'Student Center',
    isPrivate: true,
    tags: ['writing', 'peer-review', 'essays'],
    createdBy: 'Carol Davis',
    createdAt: '2024-09-25T00:00:00Z',
    nextMeeting: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

// Achievements & Badges
export const mockAchievements = [
  {
    id: 'achieve-1',
    name: 'Early Bird',
    description: 'Submit 5 assignments before the due date',
    icon: '🌅',
    category: 'assignments',
    progress: 5,
    total: 5,
    unlocked: true,
    unlockedAt: '2024-10-15T00:00:00Z',
    points: 50,
    rarity: 'common',
  },
  {
    id: 'achieve-2',
    name: 'Perfect Score',
    description: 'Earn 100% on any assignment',
    icon: '🎯',
    category: 'grades',
    progress: 1,
    total: 1,
    unlocked: true,
    unlockedAt: '2024-11-01T00:00:00Z',
    points: 100,
    rarity: 'rare',
  },
  {
    id: 'achieve-3',
    name: 'Discussion Star',
    description: 'Create 10 discussion posts',
    icon: '⭐',
    category: 'engagement',
    progress: 7,
    total: 10,
    unlocked: false,
    points: 75,
    rarity: 'uncommon',
  },
  {
    id: 'achieve-4',
    name: 'Study Streak',
    description: 'Log in for 30 consecutive days',
    icon: '🔥',
    category: 'engagement',
    progress: 22,
    total: 30,
    unlocked: false,
    points: 150,
    rarity: 'epic',
  },
  {
    id: 'achieve-5',
    name: 'Helping Hand',
    description: 'Help 5 classmates in discussions',
    icon: '🤝',
    category: 'collaboration',
    progress: 5,
    total: 5,
    unlocked: true,
    unlockedAt: '2024-10-20T00:00:00Z',
    points: 100,
    rarity: 'rare',
  },
  {
    id: 'achieve-6',
    name: 'Master Scholar',
    description: 'Maintain a GPA above 3.8 for a semester',
    icon: '🎓',
    category: 'grades',
    progress: 1,
    total: 1,
    unlocked: false,
    points: 250,
    rarity: 'legendary',
  },
];

export const mockBadges = [
  {
    id: 'badge-1',
    name: 'Top Contributor',
    description: 'Most helpful in CS 101 discussions',
    icon: '👑',
    courseId: '1',
    courseName: 'CS 101',
    earnedAt: '2024-11-01T00:00:00Z',
  },
  {
    id: 'badge-2',
    name: 'Assignment Master',
    description: 'Submitted all assignments on time in MATH 201',
    icon: '✅',
    courseId: '2',
    courseName: 'MATH 201',
    earnedAt: '2024-10-28T00:00:00Z',
  },
  {
    id: 'badge-3',
    name: 'Peer Reviewer',
    description: 'Provided excellent peer feedback in ENG 102',
    icon: '📝',
    courseId: '3',
    courseName: 'ENG 102',
    earnedAt: '2024-11-05T00:00:00Z',
  },
];

// Grade Calculator Data
export const mockGradeCategories = [
  { id: 'cat-1', name: 'Assignments', weight: 30, grades: [92, 88, 95, 90] },
  { id: 'cat-2', name: 'Exams', weight: 40, grades: [85, 92] },
  { id: 'cat-3', name: 'Participation', weight: 10, grades: [95, 98, 100] },
  { id: 'cat-4', name: 'Final Project', weight: 20, grades: [] }, // Not graded yet
];
