// Mock data for development and testing

export const mockUser = {
  id: '1',
  email: 'john.doe@university.edu',
  firstName: 'John',
  lastName: 'Doe',
  role: 'student' as const,
  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
  bio: 'Computer Science major passionate about AI and machine learning.',
  createdAt: '2024-01-15T00:00:00Z',
};

export const mockCourses = [
  {
    id: '1',
    code: 'CS 101',
    name: 'Introduction to Computer Science',
    description: 'Fundamental concepts of computer science including algorithms, data structures, and programming.',
    instructor: 'Dr. Sarah Smith',
    instructorId: 'inst-1',
    semester: 'Fall',
    year: 2024,
    credits: 4,
    enrollmentCount: 45,
    progress: 75,
    nextDeadline: '2 days',
    syllabus: 'https://example.com/syllabus-cs101.pdf',
    color: 'blue',
  },
  {
    id: '2',
    code: 'MATH 201',
    name: 'Calculus II',
    description: 'Advanced calculus including integration techniques, sequences, and series.',
    instructor: 'Prof. Michael Johnson',
    instructorId: 'inst-2',
    semester: 'Fall',
    year: 2024,
    credits: 4,
    enrollmentCount: 38,
    progress: 60,
    nextDeadline: '5 days',
    color: 'purple',
  },
  {
    id: '3',
    code: 'ENG 102',
    name: 'English Composition',
    description: 'Academic writing, research methods, and critical analysis.',
    instructor: 'Dr. Emily Williams',
    instructorId: 'inst-3',
    semester: 'Fall',
    year: 2024,
    credits: 3,
    enrollmentCount: 32,
    progress: 90,
    nextDeadline: '1 day',
    color: 'green',
  },
  {
    id: '4',
    code: 'PHY 201',
    name: 'Physics I',
    description: 'Mechanics, thermodynamics, and wave motion.',
    instructor: 'Dr. Robert Brown',
    instructorId: 'inst-4',
    semester: 'Fall',
    year: 2024,
    credits: 4,
    enrollmentCount: 41,
    progress: 45,
    nextDeadline: '3 days',
    color: 'red',
  },
];

export const mockModules = [
  {
    id: 'm1',
    courseId: '1',
    title: 'Introduction to Programming',
    description: 'Basic programming concepts and Python syntax',
    order: 1,
    isPublished: true,
    items: [
      { id: 'i1', type: 'lecture' as const, title: 'Variables and Data Types', duration: 45, isCompleted: true },
      { id: 'i2', type: 'assignment' as const, title: 'Practice Problems Set 1', points: 20, isCompleted: true },
      { id: 'i3', type: 'lecture' as const, title: 'Control Flow', duration: 60, isCompleted: true },
      { id: 'i4', type: 'quiz' as const, title: 'Module 1 Quiz', points: 10, isCompleted: false },
    ],
  },
  {
    id: 'm2',
    courseId: '1',
    title: 'Data Structures',
    description: 'Arrays, lists, stacks, and queues',
    order: 2,
    isPublished: true,
    items: [
      { id: 'i5', type: 'lecture' as const, title: 'Arrays and Lists', duration: 50, isCompleted: true },
      { id: 'i6', type: 'lecture' as const, title: 'Stacks and Queues', duration: 55, isCompleted: false },
      { id: 'i7', type: 'assignment' as const, title: 'Data Structures Project', points: 100, isCompleted: false, dueDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString() },
    ],
  },
  {
    id: 'm3',
    courseId: '1',
    title: 'Algorithms',
    description: 'Sorting, searching, and algorithmic complexity',
    order: 3,
    isPublished: true,
    items: [
      { id: 'i8', type: 'lecture' as const, title: 'Sorting Algorithms', duration: 70, isCompleted: false },
      { id: 'i9', type: 'lecture' as const, title: 'Big O Notation', duration: 45, isCompleted: false },
    ],
  },
];

export const mockAssignments = [
  {
    id: 'a1',
    courseId: '1',
    courseName: 'CS 101',
    title: 'Data Structures Project',
    description: 'Implement a binary search tree with insert, delete, and search operations.',
    instructions: 'Create a Python program that implements a binary search tree. Include comprehensive tests.',
    points: 100,
    dueDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    submittedAt: null,
    status: 'pending' as const,
    submissionType: 'file' as const,
    allowedFileTypes: ['.py', '.pdf'],
    maxFileSize: 10485760, // 10MB
  },
  {
    id: 'a2',
    courseId: '2',
    courseName: 'MATH 201',
    title: 'Calculus Problem Set 5',
    description: 'Integration by parts and substitution problems.',
    instructions: 'Solve all problems showing your work. Upload as PDF.',
    points: 50,
    dueDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    submittedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'submitted' as const,
    submissionType: 'file' as const,
  },
  {
    id: 'a3',
    courseId: '3',
    courseName: 'ENG 102',
    title: 'Essay: Modern Literature',
    description: 'Analyze themes in contemporary literature.',
    instructions: 'Write a 1500-word essay analyzing themes in the assigned reading.',
    points: 75,
    dueDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    submittedAt: null,
    status: 'pending' as const,
    submissionType: 'text' as const,
  },
  {
    id: 'a4',
    courseId: '4',
    courseName: 'PHY 201',
    title: 'Lab Report: Kinematics',
    description: 'Analysis of projectile motion experiment.',
    instructions: 'Write a lab report following the standard format.',
    points: 60,
    dueDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    submittedAt: null,
    status: 'pending' as const,
    submissionType: 'file' as const,
  },
];

export const mockGrades = [
  {
    id: 'g1',
    assignmentId: 'a5',
    assignmentName: 'Midterm Exam',
    courseId: '1',
    courseName: 'CS 101',
    score: 92,
    maxScore: 100,
    percentage: 92,
    letterGrade: 'A',
    feedback: 'Excellent work! Strong understanding of core concepts.',
    gradedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    category: 'Exams',
    weight: 30,
  },
  {
    id: 'g2',
    assignmentId: 'a6',
    assignmentName: 'Problem Set 4',
    courseId: '2',
    courseName: 'MATH 201',
    score: 85,
    maxScore: 100,
    percentage: 85,
    letterGrade: 'B',
    feedback: 'Good work. Review integration by parts.',
    gradedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    category: 'Homework',
    weight: 20,
  },
  {
    id: 'g3',
    assignmentId: 'a7',
    assignmentName: 'Research Paper',
    courseId: '3',
    courseName: 'ENG 102',
    score: 88,
    maxScore: 100,
    percentage: 88,
    letterGrade: 'B+',
    feedback: 'Well-written with strong analysis. Minor citation issues.',
    gradedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    category: 'Essays',
    weight: 40,
  },
  {
    id: 'g4',
    assignmentId: 'a8',
    assignmentName: 'Lab Practical',
    courseId: '4',
    courseName: 'PHY 201',
    score: 95,
    maxScore: 100,
    percentage: 95,
    letterGrade: 'A',
    feedback: 'Outstanding experimental technique and analysis.',
    gradedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    category: 'Labs',
    weight: 25,
  },
];

export const mockDiscussions = [
  {
    id: 'd1',
    courseId: '1',
    courseName: 'CS 101',
    authorId: 'user-1',
    authorName: 'Alice Johnson',
    authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alice',
    title: 'Best practices for recursion?',
    content: 'What are some tips for writing clean recursive functions? I sometimes struggle with base cases.',
    isPinned: true,
    isLocked: false,
    views: 127,
    replyCount: 8,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'd2',
    courseId: '1',
    courseName: 'CS 101',
    authorId: mockUser.id,
    authorName: `${mockUser.firstName} ${mockUser.lastName}`,
    authorAvatar: mockUser.avatar,
    title: 'Question about the midterm scope',
    content: 'Will the midterm cover linked lists and trees, or just arrays?',
    isPinned: false,
    isLocked: false,
    views: 64,
    replyCount: 3,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'd3',
    courseId: '2',
    courseName: 'MATH 201',
    authorId: 'user-3',
    authorName: 'Bob Smith',
    authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Bob',
    title: 'Integration by parts confusion',
    content: 'Can someone explain when to use integration by parts vs substitution?',
    isPinned: false,
    isLocked: false,
    views: 89,
    replyCount: 5,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const mockCalendarEvents = [
  {
    id: 'e1',
    type: 'class' as const,
    courseId: '1',
    courseName: 'CS 101',
    title: 'CS 101 Lecture',
    startTime: '2024-11-18T09:00:00Z',
    endTime: '2024-11-18T10:30:00Z',
    location: 'Room 301',
    color: 'blue',
  },
  {
    id: 'e2',
    type: 'class' as const,
    courseId: '2',
    courseName: 'MATH 201',
    title: 'MATH 201 Tutorial',
    startTime: '2024-11-18T14:00:00Z',
    endTime: '2024-11-18T15:00:00Z',
    location: 'Room 205',
    color: 'purple',
  },
  {
    id: 'e3',
    type: 'deadline' as const,
    courseId: '4',
    courseName: 'PHY 201',
    title: 'Assignment Due: Physics Lab',
    startTime: '2024-11-18T23:59:00Z',
    endTime: '2024-11-18T23:59:00Z',
    location: 'Online',
    color: 'red',
  },
  {
    id: 'e4',
    type: 'exam' as const,
    courseId: '1',
    courseName: 'CS 101',
    title: 'Midterm Exam',
    startTime: '2024-11-22T10:00:00Z',
    endTime: '2024-11-22T12:00:00Z',
    location: 'Main Hall',
    color: 'orange',
  },
  {
    id: 'e5',
    type: 'event' as const,
    title: 'Study Group - Data Structures',
    startTime: '2024-11-19T15:00:00Z',
    endTime: '2024-11-19T17:00:00Z',
    location: 'Library Room 3',
    color: 'green',
  },
];

export const mockNotifications = [
  {
    id: 'n1',
    type: 'grade' as const,
    title: 'New Grade Posted',
    message: 'Your Midterm Exam for CS 101 has been graded',
    isRead: false,
    actionUrl: '/grades',
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'n2',
    type: 'assignment' as const,
    title: 'Assignment Due Soon',
    message: 'Data Structures Project is due in 2 days',
    isRead: false,
    actionUrl: '/assignments/a1',
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'n3',
    type: 'announcement' as const,
    title: 'Midterm Schedule Updated',
    message: 'CS 101 midterm has been rescheduled',
    isRead: true,
    actionUrl: '/announcements/1',
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
];
