// Mock data for instructor/provider portal

export const mockInstructor = {
  id: 'inst-1',
  email: 'sarah.smith@university.edu',
  firstName: 'Sarah',
  lastName: 'Smith',
  role: 'instructor' as const,
  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
  bio: 'Associate Professor of Computer Science. Passionate about teaching and mentoring students.',
  department: 'Computer Science',
  officeLocation: 'CS Building, Room 305',
  officeHours: 'Tuesday & Thursday, 2:00 PM - 4:00 PM',
  createdAt: '2020-01-15T00:00:00Z',
};

export const mockCourses = [
  {
    id: '1',
    code: 'CS 101',
    name: 'Introduction to Computer Science',
    section: 'A',
    description: 'Fundamental concepts of computer science including algorithms, data structures, and programming.',
    semester: 'Fall',
    year: 2024,
    credits: 4,
    studentCount: 156,
    progress: 65,
    averageGrade: 82,
    pendingGrading: 23,
    activeStudents: 142,
    gradient: 'blue-cyan' as const,
    schedule: [
      { day: 'Monday', time: '9:00 AM - 10:30 AM', location: 'Room 301' },
      { day: 'Wednesday', time: '9:00 AM - 10:30 AM', location: 'Room 301' },
      { day: 'Friday', time: '9:00 AM - 10:30 AM', location: 'Room 301' },
    ],
  },
  {
    id: '2',
    code: 'CS 301',
    name: 'Data Structures & Algorithms',
    section: 'B',
    description: 'Advanced data structures and algorithmic techniques.',
    semester: 'Fall',
    year: 2024,
    credits: 4,
    studentCount: 89,
    progress: 58,
    averageGrade: 78,
    pendingGrading: 15,
    activeStudents: 85,
    gradient: 'purple-pink' as const,
    schedule: [
      { day: 'Tuesday', time: '2:00 PM - 3:30 PM', location: 'Room 205' },
      { day: 'Thursday', time: '2:00 PM - 3:30 PM', location: 'Room 205' },
    ],
  },
  {
    id: '3',
    code: 'CS 401',
    name: 'Machine Learning',
    section: 'A',
    description: 'Introduction to machine learning algorithms and applications.',
    semester: 'Fall',
    year: 2024,
    credits: 4,
    studentCount: 72,
    progress: 42,
    averageGrade: 85,
    pendingGrading: 8,
    activeStudents: 68,
    gradient: 'emerald-teal' as const,
    schedule: [
      { day: 'Monday', time: '2:00 PM - 4:00 PM', location: 'Lab 402' },
      { day: 'Wednesday', time: '2:00 PM - 4:00 PM', location: 'Lab 402' },
    ],
  },
];

export const mockGradingQueue = [
  {
    id: 'g1',
    studentId: 's1',
    studentName: 'Alice Johnson',
    studentAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alice',
    courseId: '1',
    courseName: 'CS 101',
    assignmentId: 'a1',
    assignmentName: 'Essay: Binary Search Trees',
    assignmentType: 'essay' as const,
    submittedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    dueDate: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    points: 100,
    priority: 'high' as const,
  },
  {
    id: 'g2',
    studentId: 's2',
    studentName: 'Bob Martinez',
    studentAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Bob',
    courseId: '1',
    courseName: 'CS 101',
    assignmentId: 'a2',
    assignmentName: 'Quiz 5: Recursion',
    assignmentType: 'quiz' as const,
    submittedAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    dueDate: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    points: 20,
    priority: 'high' as const,
  },
  {
    id: 'g3',
    studentId: 's3',
    studentName: 'Carol Wilson',
    studentAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Carol',
    courseId: '2',
    courseName: 'CS 301',
    assignmentId: 'a3',
    assignmentName: 'Project: Graph Algorithms',
    assignmentType: 'project' as const,
    submittedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    dueDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    points: 150,
    priority: 'medium' as const,
  },
  {
    id: 'g4',
    studentId: 's4',
    studentName: 'David Lee',
    studentAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David',
    courseId: '3',
    courseName: 'CS 401',
    assignmentId: 'a4',
    assignmentName: 'Assignment: Linear Regression',
    assignmentType: 'assignment' as const,
    submittedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    dueDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    points: 75,
    priority: 'low' as const,
  },
];

export const mockUpcomingClasses = [
  {
    id: 'c1',
    courseId: '1',
    courseName: 'CS 101',
    courseCode: 'CS 101',
    topic: 'Graph Algorithms',
    date: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
    startTime: '9:00 AM',
    endTime: '10:30 AM',
    location: 'Room 301',
    type: 'lecture' as const,
    prepNotes: 'Review BFS and DFS algorithms',
  },
  {
    id: 'c2',
    courseId: '2',
    courseName: 'CS 301',
    courseCode: 'CS 301',
    topic: 'Dynamic Programming',
    date: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
    startTime: '2:00 PM',
    endTime: '3:30 PM',
    location: 'Room 205',
    type: 'lecture' as const,
    prepNotes: 'Prepare Fibonacci examples',
  },
  {
    id: 'c3',
    courseId: '1',
    courseName: 'CS 101',
    courseCode: 'CS 101',
    topic: 'Office Hours',
    date: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    startTime: '2:00 PM',
    endTime: '4:00 PM',
    location: 'CS Building, Room 305',
    type: 'office-hours' as const,
  },
  {
    id: 'c4',
    courseId: '3',
    courseName: 'CS 401',
    courseCode: 'CS 401',
    topic: 'Neural Networks Lab',
    date: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    startTime: '2:00 PM',
    endTime: '4:00 PM',
    location: 'Lab 402',
    type: 'lab' as const,
    prepNotes: 'Setup TensorFlow environment',
  },
];

export const mockRecentActivity = [
  {
    id: 'ra1',
    type: 'submission' as const,
    studentName: 'Alice Johnson',
    studentAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alice',
    courseName: 'CS 101',
    action: 'submitted',
    item: 'Essay: Binary Search Trees',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'ra2',
    type: 'question' as const,
    studentName: 'Bob Martinez',
    studentAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Bob',
    courseName: 'CS 101',
    action: 'asked a question about',
    item: 'Recursion in Python',
    timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'ra3',
    type: 'completion' as const,
    studentName: 'Carol Wilson',
    studentAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Carol',
    courseName: 'CS 301',
    action: 'completed',
    item: 'Module 3: Sorting Algorithms',
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'ra4',
    type: 'discussion' as const,
    studentName: 'David Lee',
    studentAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David',
    courseName: 'CS 401',
    action: 'posted in discussion',
    item: 'Best practices for data preprocessing',
    timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'ra5',
    type: 'submission' as const,
    studentName: 'Emily Chen',
    studentAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emily',
    courseName: 'CS 301',
    action: 'submitted',
    item: 'Quiz 3: Big O Notation',
    timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
  },
];

export const mockStudentPerformance = {
  overall: {
    averageGrade: 82.4,
    totalStudents: 317,
    activeStudents: 295,
    atRiskStudents: 12,
  },
  gradeDistribution: [
    { grade: 'A', count: 89, percentage: 28 },
    { grade: 'B', count: 127, percentage: 40 },
    { grade: 'C', count: 76, percentage: 24 },
    { grade: 'D', count: 18, percentage: 6 },
    { grade: 'F', count: 7, percentage: 2 },
  ],
  engagementTrend: [
    { week: 'Week 1', score: 92 },
    { week: 'Week 2', score: 88 },
    { week: 'Week 3', score: 90 },
    { week: 'Week 4', score: 85 },
    { week: 'Week 5', score: 87 },
    { week: 'Week 6', score: 89 },
  ],
  atRiskStudents: [
    {
      id: 's5',
      name: 'John Doe',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
      courseId: '1',
      courseName: 'CS 101',
      currentGrade: 58,
      missedAssignments: 3,
      lastActive: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      riskLevel: 'high' as const,
    },
    {
      id: 's6',
      name: 'Jane Smith',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jane',
      courseId: '2',
      courseName: 'CS 301',
      currentGrade: 62,
      missedAssignments: 2,
      lastActive: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      riskLevel: 'medium' as const,
    },
  ],
};

export const mockAnnouncements = [
  {
    id: 'ann1',
    courseId: '1',
    courseName: 'CS 101',
    title: 'Midterm Exam Schedule',
    message: 'The midterm exam will be held on November 22nd in the Main Hall. Please arrive 15 minutes early.',
    priority: 'high' as const,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    isPinned: true,
  },
  {
    id: 'ann2',
    courseId: '2',
    courseName: 'CS 301',
    title: 'Guest Lecture Next Week',
    message: 'Dr. Johnson from Google will be giving a guest lecture on scalable algorithms next Tuesday.',
    priority: 'medium' as const,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    isPinned: false,
  },
  {
    id: 'ann3',
    courseId: '3',
    courseName: 'CS 401',
    title: 'Project Deadline Extended',
    message: 'Due to popular request, the ML project deadline has been extended by one week.',
    priority: 'low' as const,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    isPinned: false,
  },
];

export const mockCalendarEvents = [
  {
    id: 'e1',
    type: 'class' as const,
    courseId: '1',
    courseName: 'CS 101',
    title: 'CS 101 Lecture - Graph Algorithms',
    startTime: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
    endTime: new Date(Date.now() + 3.5 * 60 * 60 * 1000).toISOString(),
    location: 'Room 301',
    color: 'blue',
  },
  {
    id: 'e2',
    type: 'office-hours' as const,
    courseId: '1',
    courseName: 'CS 101',
    title: 'Office Hours',
    startTime: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    endTime: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000 + 2 * 60 * 60 * 1000).toISOString(),
    location: 'CS Building, Room 305',
    color: 'green',
  },
  {
    id: 'e3',
    type: 'deadline' as const,
    courseId: '2',
    courseName: 'CS 301',
    title: 'Deadline: Graph Algorithms Project',
    startTime: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    endTime: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    location: 'Online',
    color: 'red',
  },
  {
    id: 'e4',
    type: 'exam' as const,
    courseId: '1',
    courseName: 'CS 101',
    title: 'Midterm Exam',
    startTime: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    endTime: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000 + 2 * 60 * 60 * 1000).toISOString(),
    location: 'Main Hall',
    color: 'orange',
  },
];

export const mockStudentQuestions = [
  {
    id: 'q1',
    studentId: 's1',
    studentName: 'Alice Johnson',
    studentAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alice',
    courseId: '1',
    courseName: 'CS 101',
    question: 'How do I implement a binary search tree in Python?',
    topic: 'Data Structures',
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    status: 'pending' as const,
    isUrgent: false,
  },
  {
    id: 'q2',
    studentId: 's2',
    studentName: 'Bob Martinez',
    studentAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Bob',
    courseId: '1',
    courseName: 'CS 101',
    question: 'Can you explain the difference between BFS and DFS?',
    topic: 'Algorithms',
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    status: 'answered' as const,
    isUrgent: false,
  },
  {
    id: 'q3',
    studentId: 's3',
    studentName: 'Carol Wilson',
    studentAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Carol',
    courseId: '2',
    courseName: 'CS 301',
    question: 'I\'m having trouble understanding dynamic programming. Can we discuss this in office hours?',
    topic: 'Dynamic Programming',
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    status: 'pending' as const,
    isUrgent: true,
  },
];

export const mockStudents = [
  {
    id: 's1',
    name: 'Alice Johnson',
    email: 'alice.j@university.edu',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alice',
    courseId: '1',
    courseName: 'CS 101',
    enrolledDate: '2024-09-01',
    currentGrade: 92,
    assignmentsCompleted: 8,
    assignmentsTotal: 10,
    lastActive: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    status: 'active' as const,
  },
  {
    id: 's2',
    name: 'Bob Martinez',
    email: 'bob.m@university.edu',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Bob',
    courseId: '1',
    courseName: 'CS 101',
    enrolledDate: '2024-09-01',
    currentGrade: 85,
    assignmentsCompleted: 9,
    assignmentsTotal: 10,
    lastActive: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    status: 'active' as const,
  },
  {
    id: 's3',
    name: 'Carol Wilson',
    email: 'carol.w@university.edu',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Carol',
    courseId: '2',
    courseName: 'CS 301',
    enrolledDate: '2024-09-01',
    currentGrade: 78,
    assignmentsCompleted: 7,
    assignmentsTotal: 10,
    lastActive: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    status: 'active' as const,
  },
  {
    id: 's4',
    name: 'David Lee',
    email: 'david.l@university.edu',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David',
    courseId: '3',
    courseName: 'CS 401',
    enrolledDate: '2024-09-01',
    currentGrade: 88,
    assignmentsCompleted: 6,
    assignmentsTotal: 8,
    lastActive: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'active' as const,
  },
  {
    id: 's5',
    name: 'John Doe',
    email: 'john.d@university.edu',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    courseId: '1',
    courseName: 'CS 101',
    enrolledDate: '2024-09-01',
    currentGrade: 58,
    assignmentsCompleted: 4,
    assignmentsTotal: 10,
    lastActive: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'at-risk' as const,
  },
];

export const mockStats = {
  totalCourses: 3,
  totalStudents: 317,
  toGrade: 46,
  nextClass: mockUpcomingClasses[0],
  averageGrade: 82.4,
  activeRate: 93,
};
